// World SORFIX — portal data: TOP_COMPANIES catalog + JOBS_DATA listings
// Generated: June 2026 | NYSE · LSE · HKEX · TSE · SSE · SZSE · TADAWUL · NSE_IN · EURONEXT | 9 exchanges

const TOP_COMPANIES = {
  NYSE: [
    {t:'AAPL', n:'Apple Inc.', s:'Technology'},
    {t:'MSFT', n:'Microsoft Corporation', s:'Technology'},
    {t:'GOOGL', n:'Alphabet Inc.', s:'Technology'},
    {t:'AMZN', n:'Amazon.com Inc.', s:'Consumer Discret.'},
    {t:'META', n:'Meta Platforms Inc.', s:'Technology'},
    {t:'NVDA', n:'NVIDIA Corporation', s:'Technology'},
    {t:'TSLA', n:'Tesla Inc.', s:'Automotive'},
    {t:'BRK', n:'Berkshire Hathaway', s:'Financials'},
    {t:'JPM', n:'JPMorgan Chase & Co.', s:'Financials'},
    {t:'JNJ', n:'Johnson & Johnson', s:'Healthcare'},
    {t:'V', n:'Visa Inc.', s:'Financials'},
    {t:'MA', n:'Mastercard Inc.', s:'Financials'},
    {t:'UNH', n:'UnitedHealth Group', s:'Healthcare'},
    {t:'XOM', n:'Exxon Mobil Corporation', s:'Energy'},
    {t:'CVX', n:'Chevron Corporation', s:'Energy'},
    {t:'PG', n:'Procter & Gamble', s:'Consumer Staples'},
    {t:'HD', n:'The Home Depot Inc.', s:'Consumer Discret.'},
    {t:'LLY', n:'Eli Lilly and Company', s:'Healthcare'},
    {t:'ABBV', n:'AbbVie Inc.', s:'Healthcare'},
    {t:'MRK', n:'Merck & Co. Inc.', s:'Healthcare'},
    {t:'KO', n:'The Coca-Cola Company', s:'Consumer Staples'},
    {t:'PEP', n:'PepsiCo Inc.', s:'Consumer Staples'},
    {t:'TMO', n:'Thermo Fisher Scientific', s:'Healthcare'},
    {t:'COST', n:'Costco Wholesale', s:'Consumer Staples'},
    {t:'BAC', n:'Bank of America Corp.', s:'Financials'},
    {t:'WFC', n:'Wells Fargo & Company', s:'Financials'},
    {t:'GS', n:'Goldman Sachs Group', s:'Financials'},
    {t:'MS', n:'Morgan Stanley', s:'Financials'},
    {t:'AVGO', n:'Broadcom Inc.', s:'Technology'},
    {t:'ORCL', n:'Oracle Corporation', s:'Technology'},
    {t:'CSCO', n:'Cisco Systems Inc.', s:'Technology'},
    {t:'IBM', n:'IBM Corporation', s:'Technology'},
    {t:'INTC', n:'Intel Corporation', s:'Technology'},
    {t:'AMD', n:'Advanced Micro Devices', s:'Technology'},
    {t:'QCOM', n:'Qualcomm Inc.', s:'Technology'},
    {t:'TXN', n:'Texas Instruments', s:'Technology'},
    {t:'NOW', n:'ServiceNow Inc.', s:'Technology'},
    {t:'CRM', n:'Salesforce Inc.', s:'Technology'},
    {t:'ADBE', n:'Adobe Inc.', s:'Technology'},
    {t:'NFLX', n:'Netflix Inc.', s:'Communication'},
    {t:'DIS', n:'The Walt Disney Company', s:'Communication'},
    {t:'WMT', n:'Walmart Inc.', s:'Consumer Staples'},
    {t:'NKE', n:'Nike Inc.', s:'Consumer Discret.'},
    {t:'MCD', n:"McDonald's Corporation", s:'Consumer Discret.'},
    {t:'SBUX', n:'Starbucks Corporation', s:'Consumer Discret.'},
    {t:'BA', n:'Boeing Company', s:'Industrials'},
    {t:'CAT', n:'Caterpillar Inc.', s:'Industrials'},
    {t:'GE', n:'GE Aerospace', s:'Industrials'},
    {t:'HON', n:'Honeywell International', s:'Industrials'},
    {t:'UPS', n:'United Parcel Service', s:'Industrials'},
    {t:'LMT', n:'Lockheed Martin', s:'Industrials'},
    {t:'NEE', n:'NextEra Energy Inc.', s:'Utilities'},
    {t:'AMT', n:'American Tower Corp.', s:'Real Estate'},
    {t:'FCX', n:'Freeport-McMoRan Inc.', s:'Materials'},
    {t:'LIN', n:'Linde plc', s:'Materials'},
    {t:'COP', n:'ConocoPhillips', s:'Energy'},
    {t:'PFE', n:'Pfizer Inc.', s:'Healthcare'},
    {t:'AMGN', n:'Amgen Inc.', s:'Healthcare'},
    {t:'BLK', n:'BlackRock Inc.', s:'Financials'},
    {t:'AXP', n:'American Express Company', s:'Financials'},
    {t:'SPGI', n:'S&P Global Inc.', s:'Financials'},
    {t:'CME', n:'CME Group Inc.', s:'Financials'},
    {t:'PYPL', n:'PayPal Holdings Inc.', s:'Financials'},
    {t:'UBER', n:'Uber Technologies Inc.', s:'Technology'},
    {t:'NFLXH', n:'Netflix Holdings', s:'Communication'},
    {t:'ABNB', n:'Airbnb Inc.', s:'Consumer Discret.'},
    {t:'COIN', n:'Coinbase Global Inc.', s:'Financials'},
    {t:'SPOT', n:'Spotify Technology', s:'Communication'},
    {t:'SLB', n:'SLB (Schlumberger)', s:'Energy'},
    {t:'DE', n:'Deere & Company', s:'Industrials'},
    {t:'MMM', n:'3M Company', s:'Industrials'},
    {t:'RTX', n:'RTX Corporation', s:'Industrials'},
    {t:'MDT', n:'Medtronic plc', s:'Healthcare'},
    {t:'ICE', n:'Intercontinental Exchange', s:'Financials'},
    {t:'TGT', n:'Target Corporation', s:'Consumer Discret.'},
    {t:'MMC', n:'Marsh & McLennan', s:'Financials'},
    {t:'T', n:'AT&T Inc.', s:'Communication'},
    {t:'VZ', n:'Verizon Communications', s:'Communication'},
    {t:'DUK', n:'Duke Energy Corporation', s:'Utilities'},
    {t:'SO', n:'Southern Company', s:'Utilities'},
    {t:'OXY', n:'Occidental Petroleum', s:'Energy'},
    {t:'GILD', n:'Gilead Sciences Inc.', s:'Healthcare'},
    {t:'AON', n:'Aon plc', s:'Financials'},
    {t:'BKNG', n:'Booking Holdings Inc.', s:'Consumer Discret.'},
    {t:'REGN', n:'Regeneron Pharmaceuticals', s:'Healthcare'},
    {t:'ISRG', n:'Intuitive Surgical Inc.', s:'Healthcare'},
    {t:'CB', n:'Chubb Limited', s:'Financials'},
    {t:'ETN', n:'Eaton Corporation plc', s:'Industrials'},
    {t:'NSC', n:'Norfolk Southern Corporation', s:'Industrials'},
    {t:'WM', n:'Waste Management Inc.', s:'Industrials'},
    {t:'EMR', n:'Emerson Electric Co.', s:'Industrials'},
    {t:'D', n:'Dominion Energy Inc.', s:'Utilities'},
    {t:'EXC', n:'Exelon Corporation', s:'Utilities'},
    {t:'PLD', n:'Prologis Inc.', s:'Real Estate'},
    {t:'SNOW', n:'Snowflake Inc.', s:'Technology'},
    {t:'PLTR', n:'Palantir Technologies Inc.', s:'Technology'},
    {t:'SHOP', n:'Shopify Inc.', s:'Technology'},
    {t:'ZM', n:'Zoom Video Communications', s:'Technology'},
    {t:'SQ', n:'Block Inc.', s:'Financials'},
    {t:'ROKU', n:'Roku Inc.', s:'Technology'},
  ],
  LSE: [
    {t:'SHEL', n:'Shell plc', s:'Energy'},
    {t:'HSBA', n:'HSBC Holdings plc', s:'Financials'},
    {t:'ULVR', n:'Unilever plc', s:'Consumer Staples'},
    {t:'AZN', n:'AstraZeneca plc', s:'Healthcare'},
    {t:'BP', n:'BP plc', s:'Energy'},
    {t:'RIO', n:'Rio Tinto plc', s:'Materials'},
    {t:'LSEG', n:'London Stock Exchange Group', s:'Financials'},
    {t:'GSK', n:'GSK plc', s:'Healthcare'},
    {t:'BT', n:'BT Group plc', s:'Communication'},
    {t:'BARC', n:'Barclays plc', s:'Financials'},
    {t:'LLOY', n:'Lloyds Banking Group', s:'Financials'},
    {t:'NWG', n:'NatWest Group plc', s:'Financials'},
    {t:'STAN', n:'Standard Chartered plc', s:'Financials'},
    {t:'PRU', n:'Prudential plc', s:'Financials'},
    {t:'LGEN', n:'Legal & General Group', s:'Financials'},
    {t:'AV', n:'Aviva plc', s:'Financials'},
    {t:'DGE', n:'Diageo plc', s:'Consumer Staples'},
    {t:'BATS', n:'British American Tobacco', s:'Consumer Staples'},
    {t:'IMB', n:'Imperial Brands plc', s:'Consumer Staples'},
    {t:'MKS', n:'Marks & Spencer Group', s:'Consumer Discret.'},
    {t:'TSCO', n:'Tesco plc', s:'Consumer Staples'},
    {t:'SBRY', n:"Sainsbury's (J) plc", s:'Consumer Staples'},
    {t:'WPP', n:'WPP plc', s:'Communication'},
    {t:'VOD', n:'Vodafone Group plc', s:'Communication'},
    {t:'BA_', n:'BAE Systems plc', s:'Industrials'},
    {t:'RR', n:'Rolls-Royce Holdings', s:'Industrials'},
    {t:'CRH', n:'CRH plc', s:'Materials'},
    {t:'GLEN', n:'Glencore plc', s:'Materials'},
    {t:'AAL', n:'Anglo American plc', s:'Materials'},
    {t:'BHP', n:'BHP Group plc', s:'Materials'},
    {t:'ANTO', n:'Antofagasta plc', s:'Materials'},
    {t:'FRES', n:'Fresnillo plc', s:'Materials'},
    {t:'SVT', n:'Severn Trent plc', s:'Utilities'},
    {t:'UU', n:'United Utilities Group', s:'Utilities'},
    {t:'NG', n:'National Grid plc', s:'Utilities'},
    {t:'SSE', n:'SSE plc', s:'Utilities'},
    {t:'CNA', n:'Centrica plc', s:'Utilities'},
    {t:'SGE', n:'Sage Group plc', s:'Technology'},
    {t:'AUTO', n:'Auto Trader Group', s:'Technology'},
    {t:'EXPN', n:'Experian plc', s:'Technology'},
    {t:'REL', n:'RELX plc', s:'Communication'},
    {t:'PSON', n:'Pearson plc', s:'Communication'},
    {t:'MNG', n:'M&G plc', s:'Financials'},
    {t:'ABDN', n:'abrdn plc', s:'Financials'},
    {t:'ITV', n:'ITV plc', s:'Communication'},
    {t:'MNDI', n:'Mondi plc', s:'Materials'},
    {t:'NXT', n:'Next plc', s:'Consumer Discret.'},
    {t:'OCDO', n:'Ocado Group plc', s:'Consumer Discret.'},
    {t:'JD_', n:'JD Sports Fashion', s:'Consumer Discret.'},
    {t:'DCC', n:'DCC plc', s:'Energy'},
    {t:'AHT', n:'Ashtead Group plc', s:'Industrials'},
    {t:'CPG', n:'Compass Group plc', s:'Consumer Staples'},
    {t:'BNZL', n:'Bunzl plc', s:'Industrials'},
    {t:'BRBY', n:'Burberry Group plc', s:'Consumer Discret.'},
    {t:'WTB', n:'Whitbread plc', s:'Consumer Discret.'},
    {t:'IHG', n:'InterContinental Hotels Group', s:'Consumer Discret.'},
    {t:'FLTR', n:'Flutter Entertainment plc', s:'Consumer Discret.'},
    {t:'CRDA', n:'Croda International plc', s:'Materials'},
    {t:'HLMA', n:'Halma plc', s:'Technology'},
    {t:'IMI', n:'IMI plc', s:'Industrials'},
    {t:'LAND', n:'Land Securities Group plc', s:'Real Estate'},
    {t:'SGRO', n:'Segro plc', s:'Real Estate'},
    {t:'PHNX', n:'Phoenix Group Holdings plc', s:'Financials'},
    {t:'HLN', n:'Haleon plc', s:'Healthcare'},
    {t:'RTO', n:'Rentokil Initial plc', s:'Industrials'},
    {t:'BDEV', n:'Barratt Developments plc', s:'Real Estate'},
    {t:'PSN', n:'Persimmon plc', s:'Real Estate'},
    {t:'TW_', n:'Taylor Wimpey plc', s:'Real Estate'},
    {t:'BLND', n:'British Land Company plc', s:'Real Estate'},
    {t:'EMG', n:'Man Group plc', s:'Financials'},
    {t:'DPH', n:'Diploma plc', s:'Industrials'},
    {t:'CTEC', n:'ConvaTec Group plc', s:'Healthcare'},
    {t:'SPX', n:'Spirax-Sarco Engineering plc', s:'Industrials'},
    {t:'INF', n:'Informa plc', s:'Communication'},
    {t:'IAG', n:'Intl Consolidated Airlines', s:'Industrials'},
    {t:'EZJ', n:'easyJet plc', s:'Industrials'},
    {t:'HWDN', n:'Howden Joinery Group plc', s:'Consumer Discret.'},
    {t:'DLG', n:'Direct Line Insurance Group', s:'Financials'},
    {t:'SMIN', n:'Smiths Group plc', s:'Industrials'},
    {t:'BKG', n:'Berkeley Group Holdings plc', s:'Real Estate'},
    {t:'HIK', n:'Hikma Pharmaceuticals plc', s:'Healthcare'},
    {t:'ITRK', n:'Intertek Group plc', s:'Industrials'},
    {t:'RMV', n:'Rightmove plc', s:'Technology'},
    {t:'MRO', n:'Melrose Industries plc', s:'Industrials'},
    {t:'KGF', n:'Kingfisher plc', s:'Consumer Discret.'},
    {t:'STJ', n:"St James's Place plc", s:'Financials'},
    {t:'UTG', n:'Unite Group plc', s:'Real Estate'},
    {t:'LMP', n:'LondonMetric Property plc', s:'Real Estate'},
    {t:'PNN', n:'Pennon Group plc', s:'Utilities'},
    {t:'SKG', n:'Smurfit Kappa Group plc', s:'Materials'},
    {t:'WEIR', n:'Weir Group plc', s:'Industrials'},
    {t:'HSX', n:'Hiscox Ltd', s:'Financials'},
    {t:'VCT', n:'Victrex plc', s:'Materials'},
    {t:'INCH', n:'Inchcape plc', s:'Consumer Discret.'},
    {t:'SAFE', n:'Safestore Holdings plc', s:'Real Estate'},
    {t:'SMT', n:'Scottish Mortgage Inv. Trust', s:'Financials'},
    {t:'BEZ', n:'Beazley plc', s:'Financials'},
    {t:'EDV', n:'Endeavour Mining plc', s:'Materials'},
    {t:'ATST', n:'Alliance Trust plc', s:'Financials'},
    {t:'WIZZ', n:'Wizz Air Holdings plc', s:'Industrials'},
  ],
  HKEX: [
    {t:'TENCENT', n:'Tencent Holdings', s:'Technology'},
    {t:'ALIBABA', n:'Alibaba Group Holding', s:'Technology'},
    {t:'HSBCHK', n:'HSBC Holdings (HK)', s:'Financials'},
    {t:'AIA', n:'AIA Group Limited', s:'Financials'},
    {t:'CNOOC', n:'CNOOC Limited', s:'Energy'},
    {t:'BIDU', n:'Baidu Inc.', s:'Technology'},
    {t:'XIAOMI', n:'Xiaomi Corporation', s:'Technology'},
    {t:'MEITUAN', n:'Meituan', s:'Technology'},
    {t:'PING', n:'Ping An Insurance', s:'Financials'},
    {t:'BYD', n:'BYD Company Limited', s:'Automotive'},
    {t:'HKEXCO', n:'HKEX Limited', s:'Financials'},
    {t:'CKH', n:'CK Hutchison Holdings', s:'Conglomerate'},
    {t:'CATHAY', n:'Cathay Pacific Airways', s:'Transport'},
    {t:'SUNHUNG', n:'Sun Hung Kai Properties', s:'Real Estate'},
    {t:'CLP', n:'CLP Holdings Limited', s:'Utilities'},
    {t:'MTRHK', n:'MTR Corporation', s:'Transport'},
    {t:'LENOVO', n:'Lenovo Group Limited', s:'Technology'},
    {t:'ZTE', n:'ZTE Corporation', s:'Technology'},
    {t:'CTRIP', n:'Trip.com Group', s:'Consumer Discret.'},
    {t:'JD', n:'JD.com Inc.', s:'Consumer Discret.'},
    {t:'NIO', n:'NIO Inc.', s:'Automotive'},
    {t:'NETEASE', n:'NetEase Inc.', s:'Technology'},
    {t:'BILIBILI', n:'Bilibili Inc.', s:'Communication'},
    {t:'BOCHK', n:'Bank of China (HK)', s:'Financials'},
    {t:'HANGSENG', n:'Hang Seng Bank Limited', s:'Financials'},
    {t:'ICBC', n:'ICBC (HK)', s:'Financials'},
    {t:'CCB', n:'China Construction Bank', s:'Financials'},
    {t:'CMB', n:'China Merchants Bank', s:'Financials'},
    {t:'CMOBILE', n:'China Mobile Limited', s:'Communication'},
    {t:'SINOPEC', n:'Sinopec Corp.', s:'Energy'},
    {t:'PETROCHINA', n:'PetroChina Company', s:'Energy'},
    {t:'NONGFU', n:'Nongfu Spring Co.', s:'Consumer Staples'},
    {t:'MENGNIU', n:'China Mengniu Dairy', s:'Consumer Staples'},
    {t:'KUAISHOU', n:'Kuaishou Technology', s:'Technology'},
    {t:'XPEV', n:'XPeng Inc.', s:'Automotive'},
    {t:'LI_AUTO', n:'Li Auto Inc.', s:'Automotive'},
    {t:'SWIRE', n:'Swire Pacific Limited', s:'Conglomerate'},
    {t:'CHOW', n:'Chow Tai Fook Jewellery', s:'Consumer Discret.'},
    {t:'CUNICOM', n:'China Unicom (HK)', s:'Communication'},
    {t:'HKE', n:'HK Electric Investments', s:'Utilities'},
    {t:'BOC', n:'Bank of China Limited', s:'Financials'},
    {t:'WEIBO', n:'Weibo Corporation', s:'Communication'},
    {t:'PAX', n:'PAX Global Technology', s:'Technology'},
    {t:'HENDERSON', n:'Henderson Land Dev.', s:'Real Estate'},
    {t:'TOWNGAS', n:'Hong Kong & China Gas', s:'Utilities'},
    {t:'DAOHE', n:'Dah Sing Financial', s:'Financials'},
    {t:'WHARF', n:'Wharf Real Estate', s:'Real Estate'},
    {t:'LONGFOR', n:'Longfor Group Holdings', s:'Real Estate'},
    {t:'CRLAND', n:'China Resources Land', s:'Real Estate'},
    {t:'BOCOM', n:'Bank of Communications', s:'Financials'},
    {t:'ABCHK', n:'Agricultural Bank of China', s:'Financials'},
    {t:'CITIC', n:'CITIC Limited', s:'Conglomerate'},
    {t:'COSCO', n:'COSCO Shipping Holdings', s:'Transport'},
    {t:'CPIC', n:'China Pacific Insurance', s:'Financials'},
    {t:'WHEELOCK', n:'Wheelock and Company', s:'Real Estate'},
    {t:'PCCW', n:'PCCW Limited', s:'Communication'},
    {t:'CKHH', n:'CK Infrastructure Holdings', s:'Utilities'},
    {t:'LINKRST', n:'Link Real Estate Inv. Trust', s:'Real Estate'},
    {t:'CGAS', n:'China Gas Holdings', s:'Utilities'},
    {t:'SINOLAND', n:'Sino Land Company', s:'Real Estate'},
    {t:'GWM', n:'Great Wall Motor Company', s:'Automotive'},
    {t:'COLAND', n:'China Overseas Land', s:'Real Estate'},
    {t:'WUXI', n:'WuXi AppTec Co.', s:'Healthcare'},
    {t:'ANTA', n:'ANTA Sports Products', s:'Consumer Discret.'},
    {t:'LINING', n:'Li Ning Company Limited', s:'Consumer Discret.'},
    {t:'GALXY', n:'Galaxy Entertainment Group', s:'Consumer Discret.'},
    {t:'SANDSCK', n:'Sands China Ltd', s:'Consumer Discret.'},
    {t:'WYNMAC', n:'Wynn Macau Limited', s:'Consumer Discret.'},
    {t:'SJM', n:'SJM Holdings Limited', s:'Consumer Discret.'},
    {t:'MGMHK', n:'MGM China Holdings', s:'Consumer Discret.'},
    {t:'MELCO', n:'Melco Resorts & Entertainment', s:'Consumer Discret.'},
    {t:'CINDA', n:'China Cinda Asset Management', s:'Financials'},
    {t:'HUANENG', n:'Huaneng Power International', s:'Utilities'},
    {t:'ZHONGAN', n:'ZhongAn Online P&C Insurance', s:'Financials'},
    {t:'BUDAPAC', n:'Budweiser Brewing APAC', s:'Consumer Staples'},
    {t:'TINGYI', n:'Tingyi (Cayman Is.) Holding', s:'Consumer Staples'},
    {t:'WANTWANT', n:'Want Want China Holdings', s:'Consumer Staples'},
    {t:'FEIHE', n:'China Feihe Limited', s:'Consumer Staples'},
    {t:'SMOORE', n:'Smoore International Holdings', s:'Technology'},
    {t:'RAZER', n:'Razer Inc.', s:'Technology'},
    {t:'HAECO', n:'HAECO Holdings Limited', s:'Industrials'},
    {t:'GEELY', n:'Geely Automobile Holdings', s:'Automotive'},
    {t:'SHENHUA', n:'China Shenhua Energy', s:'Energy'},
    {t:'CHALCO', n:'Aluminum Corp. of China', s:'Materials'},
    {t:'CRCC', n:'China Railway Construction', s:'Industrials'},
    {t:'SMICOR', n:'SMIC Holdings', s:'Technology'},
    {t:'CRBEER', n:'China Resources Beer', s:'Consumer Staples'},
    {t:'SINOPH', n:'Sinopharm Group Co.', s:'Healthcare'},
    {t:'CIFI', n:'CIFI Holdings Group', s:'Real Estate'},
    {t:'SUNAC', n:'Sunac China Holdings', s:'Real Estate'},
    {t:'DATANG', n:'Datang Intl Power Generation', s:'Utilities'},
    {t:'CSPC', n:'CSPC Pharmaceutical Group', s:'Healthcare'},
    {t:'CONCH', n:'Anhui Conch Cement Co.', s:'Materials'},
    {t:'VANKE', n:'China Vanke Co. Ltd.', s:'Real Estate'},
    {t:'DONGFENG', n:'Dongfeng Motor Group', s:'Automotive'},
    {t:'CHINATELE', n:'China Telecom Corporation', s:'Communication'},
    {t:'HAIER', n:'Haier Smart Home Co.', s:'Technology'},
    {t:'POWER', n:'Power Assets Holdings', s:'Utilities'},
    {t:'ORIENT', n:'Orient Overseas International', s:'Transport'},
    {t:'CNOOC_GAS', n:'ENN Energy Holdings', s:'Utilities'},
  ],
  TSE: [
    {t:'TOYOTA', n:'Toyota Motor Corporation', s:'Automotive'},
    {t:'SONY', n:'Sony Group Corporation', s:'Technology'},
    {t:'SOFTBANK', n:'SoftBank Group Corp.', s:'Technology'},
    {t:'KEYENCE', n:'Keyence Corporation', s:'Technology'},
    {t:'RECRUIT', n:'Recruit Holdings Co.', s:'Technology'},
    {t:'MUFG', n:'Mitsubishi UFJ Financial', s:'Financials'},
    {t:'HONDA', n:'Honda Motor Co. Ltd.', s:'Automotive'},
    {t:'NINTENDO', n:'Nintendo Co. Ltd.', s:'Technology'},
    {t:'FANUC', n:'Fanuc Corporation', s:'Industrials'},
    {t:'CANON', n:'Canon Inc.', s:'Technology'},
    {t:'FAST', n:'Fast Retailing (Uniqlo)', s:'Consumer Discret.'},
    {t:'KDDI', n:'KDDI Corporation', s:'Communication'},
    {t:'NTT', n:'Nippon Telegraph & Tel.', s:'Communication'},
    {t:'PANASONIC', n:'Panasonic Holdings', s:'Technology'},
    {t:'HITACHI', n:'Hitachi Ltd.', s:'Industrials'},
    {t:'FUJITSU', n:'Fujitsu Limited', s:'Technology'},
    {t:'MURATA', n:'Murata Manufacturing', s:'Technology'},
    {t:'SHIN_ETSU', n:'Shin-Etsu Chemical', s:'Materials'},
    {t:'DAIKIN', n:'Daikin Industries', s:'Industrials'},
    {t:'KOMATSU', n:'Komatsu Ltd.', s:'Industrials'},
    {t:'SUZUKI', n:'Suzuki Motor Corporation', s:'Automotive'},
    {t:'SUBARU', n:'Subaru Corporation', s:'Automotive'},
    {t:'MAZDA', n:'Mazda Motor Corporation', s:'Automotive'},
    {t:'NISSAN', n:'Nissan Motor Co. Ltd.', s:'Automotive'},
    {t:'MITSUI', n:'Mitsui & Co. Ltd.', s:'Conglomerate'},
    {t:'ITOCHU', n:'ITOCHU Corporation', s:'Conglomerate'},
    {t:'SUMITOMO', n:'Sumitomo Corporation', s:'Conglomerate'},
    {t:'MARUBENI', n:'Marubeni Corporation', s:'Conglomerate'},
    {t:'ASAHI', n:'Asahi Group Holdings', s:'Consumer Staples'},
    {t:'KIRIN', n:'Kirin Holdings Company', s:'Consumer Staples'},
    {t:'AJINOMOTO', n:'Ajinomoto Co. Inc.', s:'Consumer Staples'},
    {t:'SHISEIDO', n:'Shiseido Company Ltd.', s:'Consumer Staples'},
    {t:'NOMURA', n:'Nomura Holdings Inc.', s:'Financials'},
    {t:'DAIWA', n:'Daiwa Securities Group', s:'Financials'},
    {t:'SMFG', n:'Sumitomo Mitsui Financial', s:'Financials'},
    {t:'MIZUHO', n:'Mizuho Financial Group', s:'Financials'},
    {t:'TOKIO', n:'Tokio Marine Holdings', s:'Financials'},
    {t:'ORIX', n:'ORIX Corporation', s:'Financials'},
    {t:'RESONA', n:'Resona Holdings Inc.', s:'Financials'},
    {t:'SHIMANO', n:'Shimano Inc.', s:'Consumer Discret.'},
    {t:'TDK', n:'TDK Corporation', s:'Technology'},
    {t:'KYOCERA', n:'Kyocera Corporation', s:'Technology'},
    {t:'NEC', n:'NEC Corporation', s:'Technology'},
    {t:'EBARA', n:'Ebara Corporation', s:'Industrials'},
    {t:'ROHM', n:'ROHM Co. Ltd.', s:'Technology'},
    {t:'SOFTBANKM', n:'SoftBank Corp. (Mobile)', s:'Communication'},
    {t:'MS_AD', n:'MS&AD Insurance Group', s:'Financials'},
    {t:'SOMPO', n:'Sompo Holdings Inc.', s:'Financials'},
    {t:'OLYMPUS', n:'Olympus Corporation', s:'Healthcare'},
    {t:'FUJIFILM', n:'Fujifilm Holdings Corp.', s:'Technology'},
    {t:'RICOH', n:'Ricoh Company Ltd.', s:'Technology'},
    {t:'SECOM', n:'Secom Co. Ltd.', s:'Industrials'},
    {t:'NIDEC', n:'Nidec Corporation', s:'Technology'},
    {t:'TORAY', n:'Toray Industries Inc.', s:'Materials'},
    {t:'ASAHI_K', n:'Asahi Kasei Corporation', s:'Materials'},
    {t:'KUBOTA', n:'Kubota Corporation', s:'Industrials'},
    {t:'MITSUBISHI', n:'Mitsubishi Corporation', s:'Conglomerate'},
    {t:'MIT_ELEC', n:'Mitsubishi Electric Corp.', s:'Industrials'},
    {t:'DENSO', n:'Denso Corporation', s:'Automotive'},
    {t:'AISIN', n:'Aisin Corporation', s:'Automotive'},
    {t:'YOKOGAWA', n:'Yokogawa Electric Corp.', s:'Technology'},
    {t:'DAIFUKU', n:'Daifuku Co. Ltd.', s:'Industrials'},
    {t:'DISCO', n:'Disco Corporation', s:'Technology'},
    {t:'LASERTEC', n:'Lasertec Corporation', s:'Technology'},
    {t:'SMC_CORP', n:'SMC Corporation', s:'Industrials'},
    {t:'HOYA', n:'Hoya Corporation', s:'Healthcare'},
    {t:'SYSMEX', n:'Sysmex Corporation', s:'Healthcare'},
    {t:'EISAI', n:'Eisai Co. Ltd.', s:'Healthcare'},
    {t:'TAKEDA', n:'Takeda Pharmaceutical Co.', s:'Healthcare'},
    {t:'ASTELLAS', n:'Astellas Pharma Inc.', s:'Healthcare'},
    {t:'DAIICHI', n:'Daiichi Sankyo Co. Ltd.', s:'Healthcare'},
    {t:'NSC_STEEL', n:'Nippon Steel Corporation', s:'Materials'},
    {t:'JFE', n:'JFE Holdings Inc.', s:'Materials'},
    {t:'KOITO', n:'Koito Manufacturing Co.', s:'Industrials'},
    {t:'MAKITA', n:'Makita Corporation', s:'Industrials'},
    {t:'AMADA', n:'Amada Holdings Co. Ltd.', s:'Industrials'},
    {t:'THK', n:'THK Co. Ltd.', s:'Industrials'},
    {t:'ISUZU', n:'Isuzu Motors Limited', s:'Automotive'},
    {t:'KAWASAKI', n:'Kawasaki Heavy Industries', s:'Industrials'},
    {t:'NIPPON_EX', n:'Nippon Express Holdings', s:'Transport'},
    {t:'YAMATO', n:'Yamato Holdings Co.', s:'Transport'},
    {t:'SG_HLD', n:'SG Holdings Co. Ltd.', s:'Transport'},
    {t:'ANA', n:'ANA Holdings Inc.', s:'Transport'},
    {t:'JAL', n:'Japan Airlines Co.', s:'Transport'},
    {t:'RYOHIN', n:'Ryohin Keikaku Co. (MUJI)', s:'Consumer Discret.'},
    {t:'NITORI', n:'Nitori Holdings Co.', s:'Consumer Discret.'},
    {t:'YAMAHA', n:'Yamaha Corporation', s:'Consumer Discret.'},
    {t:'YAMAHA_M', n:'Yamaha Motor Co. Ltd.', s:'Automotive'},
    {t:'SUNTORY', n:'Suntory Beverage & Food', s:'Consumer Staples'},
    {t:'MEIJI', n:'Meiji Holdings Co. Ltd.', s:'Consumer Staples'},
    {t:'YAKULT', n:'Yakult Honsha Co. Ltd.', s:'Consumer Staples'},
    {t:'NPH', n:'Nippon Paint Holdings', s:'Materials'},
    {t:'TOTO', n:'TOTO Ltd.', s:'Industrials'},
    {t:'JSR', n:'JSR Corporation', s:'Materials'},
    {t:'HANKYU', n:'Hankyu Hanshin Holdings', s:'Transport'},
    {t:'TOKYU', n:'Tokyu Corporation', s:'Real Estate'},
    {t:'SEGA', n:'Sega Sammy Holdings', s:'Technology'},
    {t:'CAPCOM', n:'Capcom Co. Ltd.', s:'Technology'},
    {t:'SQUARE_EN', n:'Square Enix Holdings', s:'Technology'},
    {t:'KDDI_OW', n:'Otsuka Holdings Co.', s:'Healthcare'},
  ],
  SSE: [
    {t:'MOUTAI',n:'Kweichow Moutai',s:'Consumer Staples'},
    {t:'ICBC_A',n:'ICBC (A Share)',s:'Financials'},
    {t:'PINGAN',n:'Ping An Insurance',s:'Financials'},
    {t:'CCB_A',n:'China Construction Bank (A)',s:'Financials'},
    {t:'CMOBILE_A',n:'China Mobile (A)',s:'Communication'},
    {t:'PETROCHINA_A',n:'PetroChina (A)',s:'Energy'},
    {t:'WANHUA',n:'Wanhua Chemical Group',s:'Materials'},
    {t:'BAOSHAN',n:'Baoshan Iron & Steel',s:'Materials'},
    {t:'CMB_A',n:'China Merchants Bank (A)',s:'Financials'},
    {t:'MIDEA_A',n:'Midea Group (A)',s:'Industrials'},
  ],
  SZSE: [
    {t:'BYD_A',n:'BYD Co. (A Share)',s:'Automotive'},
    {t:'CATL',n:'CATL',s:'Technology'},
    {t:'HIKVISION',n:'Hikvision',s:'Technology'},
    {t:'MINDRAY',n:'Mindray Medical',s:'Healthcare'},
    {t:'LUXSHARE',n:'Luxshare Precision',s:'Technology'},
    {t:'LONGi_GRN',n:'LONGi Green Energy',s:'Energy'},
    {t:'SUNGROW',n:'Sungrow Power Supply',s:'Energy'},
    {t:'ASML',n:'NAURA Technology',s:'Technology'},
    {t:'EVE_ENERGY',n:'EVE Energy',s:'Technology'},
    {t:'HENGRUI',n:'Jiangsu Hengrui Medicine',s:'Healthcare'},
  ],
  TADAWUL: [
    {t:'ARAMCO',n:'Saudi Aramco',s:'Energy'},
    {t:'SNB',n:'Saudi National Bank',s:'Financials'},
    {t:'RAJHI',n:'Al Rajhi Bank',s:'Financials'},
    {t:'SABIC',n:'SABIC',s:'Materials'},
    {t:'STC',n:'Saudi Telecom',s:'Communication'},
    {t:'MAADEN',n:"Saudi Arabian Mining (Ma'aden)",s:'Materials'},
    {t:'LOREAL',n:'ACWA Power',s:'Utilities'},
    {t:'ALMARAI',n:'Almarai Company',s:'Consumer Staples'},
    {t:'BUPA_ARABIA',n:'Bupa Arabia',s:'Financials'},
    {t:'DALLAH',n:'Dallah Healthcare',s:'Healthcare'},
  ],
  NSE_IN: [
    {t:'RELIANCE',n:'Reliance Industries',s:'Energy'},
    {t:'TCS',n:'Tata Consultancy Services',s:'Technology'},
    {t:'HDFCBANK',n:'HDFC Bank',s:'Financials'},
    {t:'INFY',n:'Infosys',s:'Technology'},
    {t:'ICICIBANK',n:'ICICI Bank',s:'Financials'},
    {t:'BAJFINANCE',n:'Bajaj Finance',s:'Financials'},
    {t:'BHARTIARTL',n:'Bharti Airtel',s:'Communication'},
    {t:'LT',n:'Larsen & Toubro',s:'Industrials'},
    {t:'ASIANPAINT',n:'Asian Paints',s:'Materials'},
    {t:'MARUTI',n:'Maruti Suzuki',s:'Automotive'},
  ],
  EURONEXT: [
    {t:'LVMH',n:'LVMH',s:'Consumer Discret.'},
    {t:'ASML',n:'ASML Holding',s:'Technology'},
    {t:'TOTALENERGIES',n:'TotalEnergies',s:'Energy'},
    {t:'SANOFI',n:'Sanofi',s:'Healthcare'},
    {t:'AIRBUS',n:'Airbus',s:'Industrials'},
    {t:'HERMES',n:'Hermes International',s:'Consumer Discret.'},
    {t:'LOREAL',n:"L'Oreal",s:'Consumer Staples'},
    {t:'SCHNEIDER',n:'Schneider Electric',s:'Industrials'},
    {t:'BNPPARIBAS',n:'BNP Paribas',s:'Financials'},
    {t:'AIR_LIQUIDE',n:'Air Liquide',s:'Materials'},
  ],
};

// ── Live job listings — featured companies (sourced June 2026) ──────────────

const JOBS_DATA = {

  // ── NYSE — United States ─────────────────────────────────────────────────────
  AAPL: [
    { id:'AAPL-001', title:'Senior Software Engineer — iOS Platform',    dept:'Software Engineering', location:'Cupertino, CA, USA',  type:'Full-time', posted:'2026-05-20', deadline:'2026-07-15', summary:'Build core iOS platform frameworks used by billions of devices worldwide. Deep expertise in Swift, Objective-C, and Apple platform internals required.' },
    { id:'AAPL-002', title:'Machine Learning Researcher — Siri',          dept:'AI/ML',                location:'Seattle, WA, USA',    type:'Full-time', posted:'2026-05-15', deadline:'2026-07-01', summary:'Advance on-device intelligence powering Siri across Apple devices. PhD in ML/NLP and strong publications record preferred.' },
    { id:'AAPL-003', title:'Hardware Engineer — Silicon Design',          dept:'Hardware Engineering', location:'Cupertino, CA, USA',  type:'Full-time', posted:'2026-05-10', deadline:'2026-06-30', summary:'Design next-generation Apple Silicon SoCs. Experience with RTL design, synthesis, and physical implementation required.' },
    { id:'AAPL-004', title:'Product Manager — App Store',                 dept:'Product Management',   location:'Cupertino, CA, USA',  type:'Full-time', posted:'2026-05-25', deadline:'2026-07-20', summary:'Drive App Store developer tools and business model evolution. 5+ yrs product management in platform or marketplace products.' },
  ],
  NVDA: [
    { id:'NVDA-001', title:'Deep Learning Infrastructure Engineer',       dept:'AI Infrastructure',    location:'Santa Clara, CA, USA', type:'Full-time', posted:'2026-05-22', deadline:'2026-07-10', summary:"Scale NVIDIA's AI training clusters to exascale. Experience with distributed systems, NCCL, and GPU cluster management required." },
    { id:'NVDA-002', title:'CUDA Software Engineer',                      dept:'Developer Tools',      location:'Santa Clara, CA, USA', type:'Full-time', posted:'2026-05-18', deadline:'2026-07-05', summary:'Design high-performance CUDA libraries used by AI researchers globally. Expert-level GPU programming and parallel computing required.' },
    { id:'NVDA-003', title:'Autonomous Vehicle Software Architect',       dept:'DRIVE Platform',       location:'Austin, TX, USA',     type:'Full-time', posted:'2026-05-12', deadline:'2026-06-28', summary:'Architect safety-critical software stacks for NVIDIA DRIVE AV platforms. Functional safety (ISO 26262) experience required.' },
    { id:'NVDA-004', title:'Graduate Researcher — AI Research Residency', dept:'Research',             location:'Remote (Global)',     type:'Full-time', posted:'2026-05-28', deadline:'2026-07-25', summary:"NVIDIA's annual research residency for PhD students. Work with world-class researchers on foundational AI problems." },
  ],
  JPM: [
    { id:'JPM-001', title:'Investment Banking Analyst — M&A',            dept:'Investment Banking',   location:'New York, NY, USA',   type:'Full-time', posted:'2026-05-15', deadline:'2026-06-30', summary:"Support JPMorgan's M&A advisory practice across sector coverage teams. Top-tier financial modelling, deal execution, and client presentation skills required." },
    { id:'JPM-002', title:'Quantitative Research Analyst',                dept:'Quantitative Research',location:'New York, NY, USA',   type:'Full-time', posted:'2026-05-08', deadline:'2026-06-22', summary:'Build pricing and risk models for structured credit and derivatives. PhD in Mathematics, Physics, or Engineering. Python/C++ expertise.' },
    { id:'JPM-003', title:'Technology VP — AI & Data Platforms',          dept:'Technology',           location:'Jersey City, NJ, USA', type:'Full-time', posted:'2026-05-20', deadline:'2026-07-05', summary:'Lead engineering teams building AI-powered trading and risk platforms. 8+ yrs tech leadership in financial services.' },
    { id:'JPM-004', title:'Global Markets Sales — Rates',                 dept:'Global Markets',       location:'London, UK',          type:'Full-time', posted:'2026-05-05', deadline:'2026-06-18', summary:'Originate and execute interest rate derivative trades for European institutional clients. 5+ yrs rates sales experience, Series 7/63 or equivalent.' },
  ],
  MSFT: [
    { id:'MSFT-001', title:'Principal Software Engineer — Azure AI',      dept:'Azure',                location:'Redmond, WA, USA',    type:'Full-time', posted:'2026-05-22', deadline:'2026-07-12', summary:'Design distributed AI inference infrastructure serving millions of Azure customers. Expertise in C++, distributed systems, and ML deployment.' },
    { id:'MSFT-002', title:'Product Manager — Microsoft 365 Copilot',     dept:'Productivity & AI',    location:'Redmond, WA, USA',    type:'Full-time', posted:'2026-05-18', deadline:'2026-07-08', summary:'Define the roadmap for AI-powered productivity features in M365. 6+ yrs PM experience in enterprise software or AI products.' },
    { id:'MSFT-003', title:'Security Researcher — Threat Intelligence',   dept:'Security',             location:'Redmond, WA, USA',    type:'Full-time', posted:'2026-05-10', deadline:'2026-06-25', summary:'Investigate nation-state threat actors and advanced persistent threats. Strong background in malware analysis, OSINT, and threat hunting.' },
  ],
  GOOGL: [
    { id:'GOOGL-001', title:'Staff Software Engineer — Search',           dept:'Search',               location:'Mountain View, CA, USA',type:'Full-time', posted:'2026-05-20', deadline:'2026-07-10', summary:"Design Google's next-generation search ranking and retrieval systems. Expertise in large-scale distributed systems, ML, and information retrieval." },
    { id:'GOOGL-002', title:'Research Scientist — Google DeepMind',       dept:'DeepMind',             location:'London, UK',          type:'Full-time', posted:'2026-05-15', deadline:'2026-07-05', summary:'Conduct frontier AI safety and alignment research. PhD in ML/AI required. Strong publication record and interest in beneficial AI.' },
    { id:'GOOGL-003', title:'Cloud Solutions Architect — GCP',            dept:'Google Cloud',         location:'San Francisco, CA',   type:'Full-time', posted:'2026-05-12', deadline:'2026-06-28', summary:'Help enterprise customers design and migrate to GCP. Deep expertise in cloud-native architecture, Kubernetes, and data platforms.' },
    { id:'GOOGL-004', title:'YouTube Creator Partner Manager',            dept:'YouTube',              location:'San Bruno, CA, USA',  type:'Full-time', posted:'2026-05-08', deadline:'2026-06-22', summary:'Manage strategic relationships with top YouTube creators. 4+ yrs experience in digital media, talent management, or creator economy.' },
  ],
  GS: [
    { id:'GS-001', title:'Securities Division Analyst — Fixed Income',    dept:'Securities',           location:'New York, NY, USA',   type:'Full-time', posted:'2026-05-18', deadline:'2026-07-02', summary:"Join Goldman's Fixed Income, Currencies & Commodities division. Analytical skills, financial markets knowledge, and Series 7 required." },
    { id:'GS-002', title:'Private Equity Associate — Growth Equity',      dept:'Merchant Banking',     location:'New York, NY, USA',   type:'Full-time', posted:'2026-05-12', deadline:'2026-06-26', summary:'Source and evaluate growth equity investments across tech and healthcare. 2-3 yrs IB/PE experience. MBA preferred.' },
    { id:'GS-003', title:'Technology Risk Analyst — Cybersecurity',       dept:'Technology Risk',      location:'Salt Lake City, UT',  type:'Full-time', posted:'2026-05-06', deadline:'2026-06-20', summary:'Assess and manage cybersecurity risk across Goldman Sachs technology platforms. CISSP or CISM certification preferred.' },
  ],

  // ── LSE — United Kingdom ─────────────────────────────────────────────────────
  SHEL: [
    { id:'SHEL-001', title:'Energy Trader — LNG',                        dept:'Trading',              location:'London, UK',          type:'Full-time', posted:'2026-05-20', deadline:'2026-07-10', summary:"Trade global LNG cargoes and manage Shell's short-term LNG portfolio. 5+ yrs commodity trading experience. Quantitative skills essential." },
    { id:'SHEL-002', title:'Renewable Energy Project Developer',          dept:'New Energies',         location:'Rotterdam, Netherlands',type:'Full-time', posted:'2026-05-15', deadline:'2026-07-01', summary:'Develop offshore wind and hydrogen projects across Europe. Engineering or project development background, 6+ yrs energy industry experience.' },
    { id:'SHEL-003', title:'Software Engineer — Digital & Technology',    dept:'Digital',              location:'London, UK',          type:'Full-time', posted:'2026-05-10', deadline:'2026-06-28', summary:"Build data platforms and trading tools powering Shell's global energy operations. Python, Scala, cloud-native architecture experience." },
    { id:'SHEL-004', title:'Graduate Programme — Engineering',            dept:'Graduate Talent',      location:'Multiple (global)',   type:'Full-time', posted:'2026-05-01', deadline:'2026-06-15', summary:"Shell's 3-year structured programme for engineering graduates. Rotations across upstream, LNG, and renewables. MEng or BEng required." },
  ],
  HSBA: [
    { id:'HSBA-001', title:'Global Markets Graduate Programme',           dept:'Graduate Talent',      location:'London, UK',          type:'Full-time', posted:'2026-05-18', deadline:'2026-07-03', summary:"Competitive 2-year rotational programme across HSBC's Global Markets divisions. Top graduates from any discipline. Series 7/63 or IMC sponsored." },
    { id:'HSBA-002', title:'Transaction Banking Director — Asia',         dept:'Global Banking',       location:'Hong Kong',           type:'Full-time', posted:'2026-05-12', deadline:'2026-06-27', summary:'Lead cash management and trade finance business development across Asia Pacific. 10+ yrs transactional banking, Mandarin a strong advantage.' },
    { id:'HSBA-003', title:'Quantitative Developer — Markets Technology', dept:'Technology',           location:'London, UK',          type:'Full-time', posted:'2026-05-06', deadline:'2026-06-20', summary:"Build low-latency pricing engines and risk systems for HSBC's rates and FX businesses. C++/Python, financial mathematics expertise." },
  ],
  AZN: [
    { id:'AZN-001', title:'Clinical Research Physician — Oncology',       dept:'Clinical Development', location:'Cambridge, UK',        type:'Full-time', posted:'2026-05-20', deadline:'2026-07-08', summary:'Lead Phase II/III oncology trials in AstraZeneca\'s biologic pipeline. MD/PhD, 5+ yrs clinical trial experience in oncology required.' },
    { id:'AZN-002', title:'Computational Biologist — Drug Discovery',     dept:'R&D',                  location:'Gaithersburg, MD, USA',type:'Full-time', posted:'2026-05-14', deadline:'2026-07-01', summary:'Apply ML and genomics to identify new drug targets. PhD in computational biology, bioinformatics, or systems biology required.' },
    { id:'AZN-003', title:'Commercial Lead — Rare Diseases',              dept:'Commercial',           location:'London, UK',          type:'Full-time', posted:'2026-05-08', deadline:'2026-06-22', summary:'Drive market access and commercial strategy for rare disease portfolio in Europe. Pharma commercial leadership experience required.' },
  ],
  GSK: [
    { id:'GSK-001', title:'Vaccine Research Scientist — mRNA Platform',  dept:'R&D',                  location:'Stevenage, UK',        type:'Full-time', posted:'2026-05-18', deadline:'2026-07-06', summary:"Advance GSK's mRNA vaccine programs from candidate identification through Phase I. PhD in molecular biology or immunology, 4+ yrs post-doctoral experience." },
    { id:'GSK-002', title:'Regulatory Affairs Manager — Biologics',       dept:'Regulatory',           location:'Brentford, UK',       type:'Full-time', posted:'2026-05-12', deadline:'2026-06-28', summary:'Prepare and manage EMA and FDA biologic licence applications. 6+ yrs regulatory affairs in the pharmaceutical industry.' },
    { id:'GSK-003', title:'Supply Chain Analyst — Global Manufacturing',  dept:'Supply Chain',         location:'Ware, UK',            type:'Full-time', posted:'2026-05-05', deadline:'2026-06-19', summary:'Optimise vaccine and medicine supply networks across 36 manufacturing sites. APICS CPIM or CSCMP certification preferred.' },
  ],
  RR: [
    { id:'RR-001', title:'Aerospace Engineer — Trent XWB Engine',        dept:'Engineering',          location:'Derby, UK',           type:'Full-time', posted:'2026-05-15', deadline:'2026-07-01', summary:'Design and certify components for Rolls-Royce civil aero engines powering the Airbus A350. MEng Aerospace or Mechanical Engineering. Catia V5 required.' },
    { id:'RR-002', title:'Graduate Engineer — Power Systems',             dept:'Graduate Talent',      location:'Derby, UK',           type:'Full-time', posted:'2026-05-10', deadline:'2026-06-25', summary:"Rolls-Royce's 3-year graduate programme across civil aerospace, defence, and power systems. BEng/MEng in an engineering discipline required." },
    { id:'RR-003', title:'Data Scientist — Engine Health Monitoring',     dept:'Digital',              location:'Bristol, UK',         type:'Full-time', posted:'2026-05-05', deadline:'2026-06-18', summary:"Build predictive models that monitor Rolls-Royce's fleet of 13,000+ in-service engines. Python, time-series ML, and aviation domain knowledge preferred." },
  ],

  // ── HKEX — Hong Kong ─────────────────────────────────────────────────────────
  TENCENT: [
    { id:'TENCENT-001', title:'Senior Product Manager — WeChat Pay',      dept:'FinTech',              location:'Shenzhen, China',      type:'Full-time', posted:'2026-05-20', deadline:'2026-07-10', summary:"Lead WeChat Pay's international expansion product roadmap. Deep knowledge of mobile payments, regulatory compliance, and Mandarin required." },
    { id:'TENCENT-002', title:'AI Research Scientist — NLP',              dept:'AI Lab',               location:'Beijing, China',       type:'Full-time', posted:'2026-05-15', deadline:'2026-07-05', summary:'Develop large language model applications across Tencent\'s ecosystem. PhD in NLP/ML. Strong publication record and LLM pre-training experience.' },
    { id:'TENCENT-003', title:'Game Developer — Unreal Engine',           dept:'Game Studios',         location:'Shanghai, China',      type:'Full-time', posted:'2026-05-10', deadline:'2026-06-28', summary:'Build AAA game titles in Tencent\'s global game studios. 5+ yrs Unreal Engine 5 development, C++, and graphics programming experience.' },
    { id:'TENCENT-004', title:'Cloud Solutions Engineer — Tencent Cloud', dept:'Cloud',                location:'Singapore',           type:'Full-time', posted:'2026-05-25', deadline:'2026-07-15', summary:"Design enterprise cloud solutions for Tencent Cloud's Southeast Asia expansion. Cloud architecture certification and bilingual (English/Mandarin) preferred." },
  ],
  ALIBABA: [
    { id:'ALIBABA-001', title:'Software Engineer — Taobao Recommendation', dept:'Algorithm Engineering',location:'Hangzhou, China',      type:'Full-time', posted:'2026-05-18', deadline:'2026-07-08', summary:"Build the recommendation algorithms serving 900M+ Taobao users. Expertise in deep learning, large-scale recommender systems, and Java/Python." },
    { id:'ALIBABA-002', title:'International Business Development — EMEA', dept:'International Commerce',location:'London, UK',          type:'Full-time', posted:'2026-05-12', deadline:'2026-07-01', summary:"Grow Alibaba's cross-border e-commerce with European brand and retailer partners. 6+ yrs BD experience in e-commerce or retail. Mandarin an advantage." },
    { id:'ALIBABA-003', title:'Alibaba Cloud — Infrastructure Engineer',   dept:'Cloud',               location:'Singapore',           type:'Full-time', posted:'2026-05-08', deadline:'2026-06-22', summary:'Design and operate Alibaba Cloud data centres across Southeast Asia. Experience with large-scale networking, cooling systems, and power management.' },
  ],
  AIA: [
    { id:'AIA-001', title:'Actuarial Analyst — Life Insurance Pricing',   dept:'Actuarial',            location:'Hong Kong',           type:'Full-time', posted:'2026-05-16', deadline:'2026-07-02', summary:"Support AIA's life product pricing across 18 Asia Pacific markets. IFoA/SOA part-qualified actuary. Experience with Prophet, Excel VBA." },
    { id:'AIA-002', title:'Digital Health Product Manager',                dept:'Digital & Innovation', location:'Hong Kong',           type:'Full-time', posted:'2026-05-10', deadline:'2026-06-26', summary:"Lead AIA's Vitality health ecosystem across Asia Pacific. 5+ yrs digital health or wellness product management experience." },
    { id:'AIA-003', title:'Investment Analyst — Fixed Income Asia',        dept:'Group Investment',     location:'Hong Kong',           type:'Full-time', posted:'2026-05-04', deadline:'2026-06-18', summary:"Manage AIA's fixed income portfolio across Asian credit markets. CFA charterholder preferred. 4+ yrs buy-side fixed income experience." },
  ],
  BYD: [
    { id:'BYD-001', title:'Battery R&D Engineer — Solid-State',           dept:'R&D',                  location:'Shenzhen, China',      type:'Full-time', posted:'2026-05-20', deadline:'2026-07-10', summary:'Develop next-generation solid-state battery technology for BYD\'s EV platforms. PhD in electrochemistry or materials science required.' },
    { id:'BYD-002', title:'Automotive Software Architect — EV Platform',  dept:'Software Engineering', location:'Xi\'an, China',        type:'Full-time', posted:'2026-05-15', deadline:'2026-07-05', summary:'Design the software architecture for BYD\'s new-energy vehicle platforms. Experience with AUTOSAR, functional safety, and embedded C++.' },
    { id:'BYD-003', title:'International Sales Manager — Europe',          dept:'International Sales',  location:'Amsterdam, Netherlands',type:'Full-time', posted:'2026-05-10', deadline:'2026-06-28', summary:"Drive BYD's EV sales growth in European markets. 6+ yrs automotive sales leadership, knowledge of European dealer networks. German/French an advantage." },
  ],
  ANTA: [
    { id:'ANTA-001', title:'Brand Marketing Manager — ANTA Pro',          dept:'Marketing',            location:'Xiamen, China',        type:'Full-time', posted:'2026-05-18', deadline:'2026-07-06', summary:"Lead ANTA's professional sports sponsorship and brand campaigns. 6+ yrs FMCG or sports brand marketing. Olympic sports knowledge an advantage." },
    { id:'ANTA-002', title:'Product Designer — Running & Training',        dept:'Product Design',       location:'Xiamen, China',        type:'Full-time', posted:'2026-05-12', deadline:'2026-06-28', summary:'Design performance footwear and apparel for ANTA\'s elite sports lines. Industrial design or footwear design degree, 5+ yrs experience required.' },
    { id:'ANTA-003', title:'E-commerce Operations Manager',                dept:'Digital Commerce',     location:'Shanghai, China',      type:'Full-time', posted:'2026-05-06', deadline:'2026-06-20', summary:'Manage ANTA\'s flagship stores on Tmall, JD.com, and Douyin. Omnichannel retail experience, strong data analytics, and campaign management skills.' },
  ],

  // ── TSE — Japan ───────────────────────────────────────────────────────────────
  TOYOTA: [
    { id:'TOYOTA-001', title:'Electrification Systems Engineer',          dept:'Powertrain Engineering',location:'Toyota City, Japan',  type:'Full-time', posted:'2026-05-20', deadline:'2026-07-10', summary:'Develop hybrid and BEV powertrain control systems for Toyota\'s next-generation vehicles. EE/ME background, embedded C experience, JLPT N3+ preferred.' },
    { id:'TOYOTA-002', title:'Software Engineer — Autonomous Driving',    dept:'Toyota Research Institute',location:'Los Altos, CA, USA', type:'Full-time', posted:'2026-05-15', deadline:'2026-07-05', summary:'Build perception and planning algorithms for autonomous vehicle platforms. PhD in robotics/ML, C++/Python, ROS experience required.' },
    { id:'TOYOTA-003', title:'Supply Chain Manager — Global Procurement', dept:'Procurement',          location:'Toyota City, Japan',  type:'Full-time', posted:'2026-05-10', deadline:'2026-06-28', summary:'Manage global supplier relationships and cost reduction programmes across Toyota\'s supply base. JLPT N2, 7+ yrs automotive procurement experience.' },
    { id:'TOYOTA-004', title:'Graduate Engineer Programme 2026',          dept:'Graduate Talent',      location:'Toyota City, Japan',  type:'Full-time', posted:'2026-05-01', deadline:'2026-06-15', summary:"Toyota's flagship graduate programme for engineering talent. Rotations across vehicle development, manufacturing, and digital transformation." },
  ],
  SONY: [
    { id:'SONY-001', title:'Imaging Sensor Architect',                    dept:'Semiconductor Solutions',location:'Kumamoto, Japan',    type:'Full-time', posted:'2026-05-22', deadline:'2026-07-12', summary:"Design next-generation CMOS image sensors for Sony's semiconductor division. PhD in EE, VLSI design experience, and knowledge of image processing algorithms." },
    { id:'SONY-002', title:'PlayStation Game Producer',                    dept:'PlayStation Studios',  location:'Tokyo, Japan / San Mateo, CA', type:'Full-time', posted:'2026-05-18', deadline:'2026-07-08', summary:'Lead production of AAA PlayStation exclusive titles from concept through launch. 8+ yrs game production, shipped 2+ titles. Bilingual (JP/EN) preferred.' },
    { id:'SONY-003', title:'Music AI Researcher — Sony CSL',              dept:'Sony Computer Science Lab',location:'Paris, France',     type:'Full-time', posted:'2026-05-12', deadline:'2026-06-28', summary:'Research AI-driven music generation and recommendation at Sony CSL Paris. PhD in machine learning, strong music theory knowledge, and audio DSP experience.' },
    { id:'SONY-004', title:'Finance Analyst — Group CFO Office',          dept:'Finance',              location:'Minato, Tokyo, Japan', type:'Full-time', posted:'2026-05-06', deadline:'2026-06-20', summary:"Support Sony Group's consolidated financial reporting and M&A analysis. CPA/CFA, USCPA or equivalent. JLPT N1 and MBA are advantageous." },
  ],
  NINTENDO: [
    { id:'NINTENDO-001', title:'Game Designer — Nintendo Switch Platform', dept:'Game Development',     location:'Kyoto, Japan',         type:'Full-time', posted:'2026-05-20', deadline:'2026-07-10', summary:"Design gameplay systems for Nintendo's first-party titles. 5+ yrs game design experience. Portfolio of shipped games required. Japanese proficiency preferred." },
    { id:'NINTENDO-002', title:'Software Engineer — Nintendo Online',     dept:'Network Services',     location:'Kyoto, Japan',         type:'Full-time', posted:'2026-05-14', deadline:'2026-07-04', summary:'Build and scale Nintendo\'s online gaming and content delivery infrastructure. 5+ yrs backend development, AWS/GCP, and JLPT N2+.' },
    { id:'NINTENDO-003', title:'Marketing Manager — European Markets',    dept:'Marketing',            location:'Frankfurt, Germany',  type:'Full-time', posted:'2026-05-08', deadline:'2026-06-22', summary:'Lead marketing campaigns for Nintendo across German-speaking markets. 6+ yrs games marketing, fluent German and English, consumer insights experience.' },
  ],
  SOFTBANK: [
    { id:'SOFTBANK-001', title:'Investment Associate — Vision Fund II',   dept:'Investment',           location:'Tokyo, Japan',         type:'Full-time', posted:'2026-05-18', deadline:'2026-07-08', summary:"Source and evaluate global tech investment opportunities for SoftBank's Vision Fund. 3+ yrs VC/PE or investment banking experience. Mandarin or Korean a plus." },
    { id:'SOFTBANK-002', title:'AI Infrastructure Architect',             dept:'Technology',           location:'Tokyo, Japan',         type:'Full-time', posted:'2026-05-12', deadline:'2026-06-28', summary:"Design AI computing infrastructure for SoftBank's portfolio companies. Expert in GPU clusters, ML frameworks, and distributed training architectures." },
    { id:'SOFTBANK-003', title:'Strategy Analyst — M&A',                 dept:'Corporate Strategy',   location:'Tokyo, Japan',         type:'Full-time', posted:'2026-05-06', deadline:'2026-06-20', summary:"Support SoftBank's global M&A and strategic partnerships. MBA from top programme, 3+ yrs strategy/IB experience, Japanese business proficiency preferred." },
  ],
  MUFG: [
    { id:'MUFG-001', title:'Global Markets Associate — FX & Rates',      dept:'Global Markets',       location:'Tokyo, Japan',         type:'Full-time', posted:'2026-05-16', deadline:'2026-07-04', summary:'Execute FX and interest rate transactions for MUFG\'s institutional clients. Series 65 or equivalent, 3+ yrs markets experience, bilingual preferred.' },
    { id:'MUFG-002', title:'Digital Banking Product Manager',             dept:'Digital Innovation',   location:'Tokyo, Japan',         type:'Full-time', posted:'2026-05-10', deadline:'2026-06-26', summary:'Build next-generation digital banking features for MUFG\'s retail app. 5+ yrs product management, fintech or banking experience, JLPT N1.' },
    { id:'MUFG-003', title:'Sustainability Finance Analyst',              dept:'Sustainable Finance',  location:'London, UK',          type:'Full-time', posted:'2026-05-04', deadline:'2026-06-18', summary:"Develop ESG-linked loan structures and green bonds across MUFG's EMEA client base. Knowledge of ICMA principles and EU Taxonomy required." },
  ],

  // ── SSE — Shanghai Stock Exchange ────────────────────────────────────────────
  MOUTAI: [
    { id:'MOUTAI-001', title:'Brand Strategy Director — International Markets', dept:'Marketing',           location:'Guiyang, China',      type:'Full-time', posted:'2026-05-18', deadline:'2026-07-08', summary:'Lead Moutai\'s luxury spirits brand strategy for export markets in Europe and North America. FMCG brand leadership and bilingual communication skills required.' },
    { id:'MOUTAI-002', title:'Digital Commerce Manager — Tmall & Douyin',       dept:'E-Commerce',          location:'Shanghai, China',     type:'Full-time', posted:'2026-05-12', deadline:'2026-07-01', summary:'Manage Moutai\'s flagship digital commerce channels. 5+ yrs e-commerce operations, campaign management, and data analytics experience on Chinese platforms.' },
    { id:'MOUTAI-003', title:'Logistics & Cold Chain Operations Lead',           dept:'Supply Chain',        location:'Guiyang, China',      type:'Full-time', posted:'2026-05-06', deadline:'2026-06-22', summary:'Optimise Moutai\'s distribution network across 31 provinces. Experience in FMCG supply chain and cold chain logistics management required.' },
  ],
  ICBC_A: [
    { id:'ICBC_A-001', title:'Investment Banking Associate — Cross-Border M&A',  dept:'Investment Banking',  location:'Beijing, China',      type:'Full-time', posted:'2026-05-20', deadline:'2026-07-10', summary:'Support M&A and capital markets transactions for Chinese SOEs and multinational clients. CFA or CPA preferred. Bilingual (Chinese/English) required.' },
    { id:'ICBC_A-002', title:'Technology Architect — Core Banking Platform',      dept:'Information Technology',location:'Shanghai, China',   type:'Full-time', posted:'2026-05-14', deadline:'2026-07-03', summary:"Architect ICBC's distributed core banking system serving 700M+ customers. 10+ yrs enterprise software architecture, Java, and microservices experience." },
    { id:'ICBC_A-003', title:'Quantitative Risk Analyst — Credit Risk',           dept:'Risk Management',     location:'Beijing, China',      type:'Full-time', posted:'2026-05-08', deadline:'2026-06-25', summary:'Build credit risk models for ICBC\'s corporate loan portfolio. PhD in Mathematics or Quantitative Finance. Python/R modelling expertise required.' },
  ],
  PINGAN: [
    { id:'PINGAN-001', title:'AI Product Manager — FinTech Platform',            dept:'Ping An Technology',  location:'Shenzhen, China',     type:'Full-time', posted:'2026-05-22', deadline:'2026-07-12', summary:'Define AI-powered product features for Ping An\'s digital financial services platform serving 230M+ personal customers. 6+ yrs product management experience.' },
    { id:'PINGAN-002', title:'Actuarial Manager — Life Insurance',                dept:'Actuarial',           location:'Shanghai, China',     type:'Full-time', posted:'2026-05-16', deadline:'2026-07-06', summary:'Price and reserve for Ping An\'s life insurance product portfolio. Qualified actuary (FCAS/FSA or Chinese equivalent). 5+ yrs life insurance actuarial experience.' },
    { id:'PINGAN-003', title:'Data Scientist — Healthcare AI',                    dept:'Ping An Good Doctor', location:'Shenzhen, China',     type:'Full-time', posted:'2026-05-10', deadline:'2026-06-28', summary:'Build clinical decision support models for Ping An\'s AI-powered healthcare platform. PhD in Data Science or Bioinformatics. Experience with medical imaging or EHR data.' },
  ],

  // ── SZSE — Shenzhen Stock Exchange ───────────────────────────────────────────
  CATL: [
    { id:'CATL-001', title:'Battery Cell Engineer — Solid-State Technology',     dept:'R&D',                 location:'Ningde, Fujian, China',type:'Full-time', posted:'2026-05-20', deadline:'2026-07-10', summary:'Develop next-generation solid-state and semi-solid battery cells for CATL\'s new product pipeline. PhD in Electrochemistry or Materials Science required.' },
    { id:'CATL-002', title:'Global Key Account Manager — European OEMs',         dept:'Sales',               location:'Munich, Germany',     type:'Full-time', posted:'2026-05-14', deadline:'2026-07-04', summary:'Manage strategic battery supply partnerships with European automotive OEMs. 8+ yrs automotive B2B sales, fluent German and English, EV technology knowledge.' },
    { id:'CATL-003', title:'Manufacturing Process Engineer — Cell Assembly',      dept:'Manufacturing',        location:'Erfurt, Germany',     type:'Full-time', posted:'2026-05-08', deadline:'2026-06-25', summary:'Optimise battery cell assembly processes at CATL\'s European gigafactory. Process engineering background in battery or electronics manufacturing. Bilingual (DE/EN).' },
  ],
  BYD_A: [
    { id:'BYD_A-001', title:'EV Powertrain Systems Engineer',                    dept:'Engineering',         location:'Shenzhen, China',     type:'Full-time', posted:'2026-05-18', deadline:'2026-07-08', summary:'Design BEV and PHEV powertrain control systems for BYD\'s Dynasty and Ocean series. Embedded systems, CAN/LIN, and functional safety (ISO 26262) expertise required.' },
    { id:'BYD_A-002', title:'International Supply Chain Manager — EV Parts',      dept:'Supply Chain',        location:'Xi\'an, China',       type:'Full-time', posted:'2026-05-12', deadline:'2026-07-01', summary:'Manage global procurement of EV components and raw materials for BYD\'s manufacturing. 6+ yrs automotive supply chain, bilingual communication skills.' },
    { id:'BYD_A-003', title:'Software Engineer — DiLink Intelligent Cockpit',     dept:'Software Engineering',location:'Shenzhen, China',     type:'Full-time', posted:'2026-05-06', deadline:'2026-06-22', summary:'Build in-vehicle infotainment and connected car software for BYD\'s DiLink platform. Android OS, automotive-grade software development, and HMI design experience.' },
  ],
  HIKVISION: [
    { id:'HIKVISION-001', title:'Computer Vision Researcher — Smart Surveillance', dept:'AI Research',       location:'Hangzhou, China',     type:'Full-time', posted:'2026-05-20', deadline:'2026-07-10', summary:'Research and develop object detection and tracking algorithms for Hikvision\'s intelligent video analysis products. PhD in Computer Vision or Deep Learning required.' },
    { id:'HIKVISION-002', title:'International Sales Engineer — EMEA',             dept:'International Sales',location:'Dubai, UAE',          type:'Full-time', posted:'2026-05-15', deadline:'2026-07-05', summary:'Develop Hikvision\'s enterprise and government video security business in the Middle East and Africa. 5+ yrs B2B sales in security technology. Arabic an advantage.' },
    { id:'HIKVISION-003', title:'Embedded Software Engineer — IoT Edge Devices',   dept:'Software Engineering',location:'Hangzhou, China',    type:'Full-time', posted:'2026-05-10', deadline:'2026-06-28', summary:'Build firmware for Hikvision\'s edge AI cameras and IoT sensors. Linux kernel, C/C++, and real-time embedded system experience required.' },
  ],

  // ── TADAWUL — Saudi Exchange ──────────────────────────────────────────────────
  ARAMCO: [
    { id:'ARAMCO-001', title:'Petroleum Engineer — Offshore Operations',          dept:'Exploration & Production',location:'Dhahran, Saudi Arabia',type:'Full-time', posted:'2026-05-18', deadline:'2026-07-08', summary:'Optimise oil recovery from Saudi Aramco\'s offshore fields. BSc/MSc in Petroleum Engineering, 5+ yrs reservoir or production engineering experience.' },
    { id:'ARAMCO-002', title:'Digital Transformation Lead — AI & Data',           dept:'Technology',          location:'Dhahran, Saudi Arabia',type:'Full-time', posted:'2026-05-12', deadline:'2026-07-01', summary:'Lead AI and advanced analytics initiatives to optimise Aramco\'s exploration and refinery operations. 10+ yrs technology leadership in the energy sector.' },
    { id:'ARAMCO-003', title:'Renewable Energy Project Developer — NEOM',         dept:'New Energies',        location:'Riyadh, Saudi Arabia', type:'Full-time', posted:'2026-05-06', deadline:'2026-06-22', summary:'Develop hydrogen and solar projects aligned with Saudi Vision 2030. Engineering background, 6+ yrs energy project development, bilingual (Arabic/English) preferred.' },
    { id:'ARAMCO-004', title:'Graduate Development Programme 2026',               dept:'Graduate Talent',     location:'Dhahran, Saudi Arabia',type:'Full-time', posted:'2026-05-01', deadline:'2026-06-15', summary:'Saudi Aramco\'s flagship 2-year graduate programme for engineering and business talent. Rotations across upstream, downstream, and corporate functions.' },
  ],
  SNB: [
    { id:'SNB-001', title:'Corporate Banking Relationship Manager',               dept:'Corporate Banking',   location:'Riyadh, Saudi Arabia', type:'Full-time', posted:'2026-05-16', deadline:'2026-07-04', summary:'Manage and grow SNB\'s large corporate client relationships in the Kingdom. 7+ yrs corporate banking, strong financial modelling, Arabic and English fluency required.' },
    { id:'SNB-002', title:'Digital Banking Product Manager — Mobile App',         dept:'Retail Banking',      location:'Riyadh, Saudi Arabia', type:'Full-time', posted:'2026-05-10', deadline:'2026-06-26', summary:'Drive SNB\'s consumer mobile banking roadmap for Vision 2030 digital economy. 5+ yrs digital product management, UX design knowledge, and Arabic fluency.' },
    { id:'SNB-003', title:'Risk Analyst — Credit Risk Modelling',                 dept:'Risk Management',     location:'Riyadh, Saudi Arabia', type:'Full-time', posted:'2026-05-04', deadline:'2026-06-18', summary:'Build IFRS 9 and Basel III credit risk models for SNB\'s corporate and retail portfolio. CFA or FRM preferred. Python/SAS modelling skills required.' },
  ],
  RAJHI: [
    { id:'RAJHI-001', title:'Islamic Finance Structurer — Sukuk',                 dept:'Capital Markets',     location:'Riyadh, Saudi Arabia', type:'Full-time', posted:'2026-05-18', deadline:'2026-07-08', summary:'Structure and execute Sukuk issuances for Al Rajhi\'s corporate and sovereign clients. 5+ yrs Islamic finance structuring experience, CFA or legal background required.' },
    { id:'RAJHI-002', title:'Retail Banking Operations Lead',                     dept:'Operations',          location:'Riyadh, Saudi Arabia', type:'Full-time', posted:'2026-05-12', deadline:'2026-07-01', summary:'Manage branch and digital operations for Al Rajhi\'s retail network serving 10M+ customers. 8+ yrs banking operations leadership, Arabic fluency essential.' },
    { id:'RAJHI-003', title:'Software Engineer — Open Banking APIs',              dept:'Technology',          location:'Riyadh, Saudi Arabia', type:'Full-time', posted:'2026-05-06', deadline:'2026-06-22', summary:'Build SAMA-compliant open banking APIs and fintech integration layer for Al Rajhi. 5+ yrs API development, RESTful services, Java/Python, and financial services experience.' },
  ],

  // ── NSE_IN — National Stock Exchange of India ─────────────────────────────────
  RELIANCE: [
    { id:'RELIANCE-001', title:'Strategy Manager — Jio Platforms',                dept:'Strategy',            location:'Mumbai, India',       type:'Full-time', posted:'2026-05-20', deadline:'2026-07-10', summary:'Shape Jio\'s digital services and 5G strategy for 450M+ subscribers. MBA from a top institute, 6+ yrs strategy/consulting in telecom or technology sector.' },
    { id:'RELIANCE-002', title:'Chemical Process Engineer — Refining',             dept:'Engineering',         location:'Jamnagar, India',     type:'Full-time', posted:'2026-05-14', deadline:'2026-07-03', summary:'Optimise operations at Reliance\'s Jamnagar refinery, the world\'s largest. BTech/MTech Chemical Engineering, 4+ yrs refinery process engineering experience.' },
    { id:'RELIANCE-003', title:'Retail Operations Manager — JioMart',             dept:'Retail',              location:'Bengaluru, India',    type:'Full-time', posted:'2026-05-08', deadline:'2026-06-25', summary:'Scale JioMart\'s hyperlocal grocery and quick commerce operations. 6+ yrs retail or e-commerce operations, supply chain logistics, and team leadership experience.' },
  ],
  TCS: [
    { id:'TCS-001', title:'Software Engineer — AI & Cloud Practice',              dept:'Engineering',         location:'Bengaluru, India',    type:'Full-time', posted:'2026-05-22', deadline:'2026-07-12', summary:'Build enterprise AI and cloud migration solutions for TCS\'s Fortune 500 clients. Java/Python, AWS/Azure expertise, and 3+ yrs software engineering experience.' },
    { id:'TCS-002', title:'Senior Consultant — Financial Services',               dept:'Consulting',          location:'London, UK / Mumbai, India', type:'Full-time', posted:'2026-05-16', deadline:'2026-07-06', summary:'Lead digital transformation engagements for global banking clients. MBA and 7+ yrs consulting in financial services. Deep knowledge of core banking systems.' },
    { id:'TCS-003', title:'Research Scientist — TCS Research',                    dept:'Research',            location:'Pune, India',         type:'Full-time', posted:'2026-05-10', deadline:'2026-06-28', summary:'Conduct applied research in AI, quantum computing, or cybersecurity for TCS\'s innovation labs. PhD in Computer Science or Engineering. Strong publication record.' },
  ],
  HDFCBANK: [
    { id:'HDFCBANK-001', title:'Product Manager — Digital Lending Platform',      dept:'Digital Banking',     location:'Mumbai, India',       type:'Full-time', posted:'2026-05-18', deadline:'2026-07-08', summary:'Build HDFC Bank\'s AI-powered digital lending and credit decisioning platform. 5+ yrs product management in fintech or banking. Data-driven, agile methodology expertise.' },
    { id:'HDFCBANK-002', title:'Relationship Manager — Private Banking',           dept:'Private Banking',     location:'Delhi NCR, India',    type:'Full-time', posted:'2026-05-12', deadline:'2026-07-01', summary:'Manage HNI and UHNI client relationships for HDFC Bank\'s private banking division. CFP or CFA, 8+ yrs wealth management or private banking experience.' },
    { id:'HDFCBANK-003', title:'Cybersecurity Analyst — SOC',                     dept:'Information Security',location:'Mumbai, India',       type:'Full-time', posted:'2026-05-06', deadline:'2026-06-22', summary:'Monitor and respond to security threats for HDFC Bank\'s enterprise infrastructure. CISSP/CEH, 4+ yrs SOC analyst experience, SIEM and threat intelligence expertise.' },
  ],
  INFY: [
    { id:'INFY-001', title:'Senior Software Engineer — Generative AI',            dept:'Engineering',         location:'Bengaluru, India',    type:'Full-time', posted:'2026-05-20', deadline:'2026-07-10', summary:'Build enterprise GenAI applications using LLMs and RAG pipelines for Infosys Nia platform. Python, LangChain, vector databases, and cloud-native architecture expertise.' },
    { id:'INFY-002', title:'Management Consultant — Digital Supply Chain',         dept:'Consulting',          location:'New York, NY, USA',   type:'Full-time', posted:'2026-05-14', deadline:'2026-07-04', summary:'Lead supply chain digital transformation for Infosys\'s North American manufacturing clients. MBA, 7+ yrs supply chain consulting, SAP S/4HANA experience preferred.' },
    { id:'INFY-003', title:'Graduate Engineer Trainee 2026',                       dept:'Graduate Talent',     location:'Multiple India locations',type:'Full-time', posted:'2026-05-01', deadline:'2026-06-15', summary:'Infosys\'s flagship GET programme for fresh engineering graduates. Structured training in software engineering, cloud, AI, and digital consulting across all verticals.' },
  ],

  // ── EURONEXT — Pan-European Exchange ─────────────────────────────────────────
  LVMH: [
    { id:'LVMH-001', title:'Digital Marketing Director — Louis Vuitton',          dept:'Digital',             location:'Paris, France',       type:'Full-time', posted:'2026-05-20', deadline:'2026-07-10', summary:'Lead Louis Vuitton\'s digital marketing strategy across social, search, and CRM. 10+ yrs luxury fashion marketing, fluent French and English, data-driven storytelling skills.' },
    { id:'LVMH-002', title:'Data Scientist — LVMH Data & AI',                    dept:'Technology',          location:'Paris, France',       type:'Full-time', posted:'2026-05-14', deadline:'2026-07-04', summary:'Build demand forecasting and personalisation models for LVMH\'s 75 Maisons. PhD in Data Science or Statistics, 4+ yrs industry experience, Python/SQL expertise.' },
    { id:'LVMH-003', title:'Supply Chain Manager — Wines & Spirits',             dept:'Operations',          location:'Bordeaux, France',    type:'Full-time', posted:'2026-05-08', deadline:'2026-06-25', summary:'Manage global logistics for Moet Hennessy\'s champagne and spirits portfolio. 6+ yrs FMCG supply chain, SAP experience, and fluent French and English.' },
  ],
  ASML: [
    { id:'ASML-001', title:'Optical Engineer — Extreme Ultraviolet Lithography',  dept:'R&D',                 location:'Veldhoven, Netherlands',type:'Full-time', posted:'2026-05-22', deadline:'2026-07-12', summary:'Design optical systems for ASML\'s EUV and High-NA EUV lithography machines. PhD in Physics or Optical Engineering. Experience with precision optics, wavefront sensing required.' },
    { id:'ASML-002', title:'Software Architect — Machine Control Systems',        dept:'Software Engineering',location:'Veldhoven, Netherlands',type:'Full-time', posted:'2026-05-16', deadline:'2026-07-06', summary:'Design safety-critical real-time control software for ASML\'s semiconductor lithography machines. C++, MISRA, and embedded real-time OS expertise. ISO 26262 or equivalent.' },
    { id:'ASML-003', title:'Customer Support Engineer — Japan & Korea',           dept:'Customer Support',    location:'Tokyo, Japan / Seoul, South Korea',type:'Full-time', posted:'2026-05-10', deadline:'2026-06-28', summary:'Install and maintain ASML machines at TSMC, Samsung, and SK Hynix fab sites. MSc in Engineering. Willingness to relocate; Japanese or Korean language skills a strong plus.' },
  ],
  TOTALENERGIES: [
    { id:'TOTALENERGIES-001', title:'Renewable Energy Project Developer — Solar', dept:'Renewables',          location:'Paris, France',       type:'Full-time', posted:'2026-05-18', deadline:'2026-07-08', summary:'Develop large-scale solar and green hydrogen projects for TotalEnergies across MENA and Africa. Engineering background, 6+ yrs renewable energy project development experience.' },
    { id:'TOTALENERGIES-002', title:'LNG Trader — Global LNG Portfolio',          dept:'Trading',             location:'Geneva, Switzerland', type:'Full-time', posted:'2026-05-12', deadline:'2026-07-01', summary:'Trade LNG cargoes for TotalEnergies\'s global portfolio across Atlantic and Pacific Basin markets. 5+ yrs commodity trading experience, quantitative analysis skills required.' },
    { id:'TOTALENERGIES-003', title:'Digital Engineer — Upstream Operations AI',  dept:'Digital & Data',      location:'Paris, France',       type:'Full-time', posted:'2026-05-06', deadline:'2026-06-22', summary:'Build predictive maintenance and production optimisation AI for TotalEnergies\' upstream operations. Python, machine learning, time-series analysis, and energy domain knowledge.' },
  ],
  SANOFI: [
    { id:'SANOFI-001', title:'Clinical Development Physician — Immunology',       dept:'Clinical Development',location:'Paris, France',       type:'Full-time', posted:'2026-05-20', deadline:'2026-07-10', summary:'Lead Phase II/III trials for Sanofi\'s immunology pipeline including dupilumab next-generation programs. MD with 5+ yrs clinical trial experience in immunology or allergy required.' },
    { id:'SANOFI-002', title:'Computational Chemist — Drug Design AI',            dept:'R&D',                 location:'Cambridge, MA, USA',  type:'Full-time', posted:'2026-05-14', deadline:'2026-07-04', summary:'Apply AI/ML to accelerate small molecule drug discovery for Sanofi\'s oncology and rare disease pipeline. PhD in Computational Chemistry, cheminformatics, or structural biology.' },
    { id:'SANOFI-003', title:'Market Access Manager — Rare Diseases Europe',      dept:'Market Access',       location:'Barcelona, Spain',    type:'Full-time', posted:'2026-05-08', deadline:'2026-06-25', summary:'Develop payer and HTA strategies for Sanofi Genzyme\'s rare disease portfolio across Southern Europe. 6+ yrs pharma market access, health economics or public health background.' },
  ],
  AIRBUS: [
    { id:'AIRBUS-001', title:'Aeronautical Engineer — A320neo Family Structure',  dept:'Engineering',         location:'Toulouse, France',    type:'Full-time', posted:'2026-05-20', deadline:'2026-07-10', summary:'Design and certify structural components for the A320neo and A321XLR aircraft. MEng Aerospace or Structural Engineering, CATIA V5/V6 experience, knowledge of EASA CS-25.' },
    { id:'AIRBUS-002', title:'Software Engineer — Avionics & FMS',               dept:'Digital Engineering', location:'Toulouse, France',    type:'Full-time', posted:'2026-05-14', deadline:'2026-07-04', summary:'Develop and verify safety-critical avionics software for Airbus aircraft flight management systems. DO-178C/C experience, C programming, ARINC 429/664 knowledge required.' },
    { id:'AIRBUS-003', title:'Hydrogen Propulsion Engineer — ZEROe Programme',   dept:'Future Projects',     location:'Toulouse, France',    type:'Full-time', posted:'2026-05-08', deadline:'2026-06-25', summary:'Design cryogenic hydrogen fuel systems for Airbus\'s ZEROe zero-emission aircraft. Aerospace or mechanical engineering background, cryogenics or propulsion system experience preferred.' },
    { id:'AIRBUS-004', title:'Graduate Programme — Engineering & Technology',     dept:'Graduate Talent',     location:'Toulouse / Hamburg / Madrid', type:'Full-time', posted:'2026-05-01', deadline:'2026-06-15', summary:'Airbus\'s structured 2-year graduate programme across aircraft design, manufacturing, and digital engineering. MEng in Aerospace or related discipline. Multilingual candidates preferred.' },
  ],
};
