"""
World SORFIX — Master company registry.
NYSE (USA) · LSE (UK) · HKEX (Hong Kong) · TSE (Japan)
SSE (Shanghai) · SZSE (Shenzhen) · TADAWUL (Saudi) · NSE_IN (India) · EURONEXT (Europe)
Each entry: symbol -> {name, sector, price (local ccy), vol (daily volatility)}
"""

COMPANIES = {
    "NYSE": {
        "AAPL":  {"name": "Apple Inc.",                   "sector": "Technology",        "price": 189.50,  "vol": 0.018},
        "MSFT":  {"name": "Microsoft Corporation",        "sector": "Technology",        "price": 415.20,  "vol": 0.016},
        "GOOGL": {"name": "Alphabet Inc.",                "sector": "Technology",        "price": 175.80,  "vol": 0.019},
        "AMZN":  {"name": "Amazon.com Inc.",              "sector": "Consumer Discret.", "price": 192.40,  "vol": 0.022},
        "META":  {"name": "Meta Platforms Inc.",          "sector": "Technology",        "price": 520.30,  "vol": 0.024},
        "NVDA":  {"name": "NVIDIA Corporation",           "sector": "Technology",        "price": 875.60,  "vol": 0.035},
        "TSLA":  {"name": "Tesla Inc.",                   "sector": "Automotive",        "price": 248.90,  "vol": 0.040},
        "BRK":   {"name": "Berkshire Hathaway",           "sector": "Financials",        "price": 415.00,  "vol": 0.012},
        "JPM":   {"name": "JPMorgan Chase & Co.",         "sector": "Financials",        "price": 198.70,  "vol": 0.015},
        "JNJ":   {"name": "Johnson & Johnson",            "sector": "Healthcare",        "price": 147.30,  "vol": 0.011},
        "V":     {"name": "Visa Inc.",                    "sector": "Financials",        "price": 278.50,  "vol": 0.014},
        "MA":    {"name": "Mastercard Inc.",              "sector": "Financials",        "price": 462.80,  "vol": 0.015},
        "UNH":   {"name": "UnitedHealth Group",           "sector": "Healthcare",        "price": 512.40,  "vol": 0.014},
        "XOM":   {"name": "Exxon Mobil Corporation",      "sector": "Energy",            "price": 117.80,  "vol": 0.018},
        "CVX":   {"name": "Chevron Corporation",          "sector": "Energy",            "price": 154.20,  "vol": 0.017},
        "PG":    {"name": "Procter & Gamble",             "sector": "Consumer Staples",  "price": 168.90,  "vol": 0.010},
        "HD":    {"name": "The Home Depot Inc.",          "sector": "Consumer Discret.", "price": 345.60,  "vol": 0.016},
        "LLY":   {"name": "Eli Lilly and Company",        "sector": "Healthcare",        "price": 798.40,  "vol": 0.025},
        "ABBV":  {"name": "AbbVie Inc.",                  "sector": "Healthcare",        "price": 175.20,  "vol": 0.016},
        "MRK":   {"name": "Merck & Co. Inc.",             "sector": "Healthcare",        "price": 128.50,  "vol": 0.013},
        "KO":    {"name": "The Coca-Cola Company",        "sector": "Consumer Staples",  "price": 61.40,   "vol": 0.009},
        "PEP":   {"name": "PepsiCo Inc.",                 "sector": "Consumer Staples",  "price": 164.80,  "vol": 0.010},
        "TMO":   {"name": "Thermo Fisher Scientific",     "sector": "Healthcare",        "price": 578.90,  "vol": 0.017},
        "COST":  {"name": "Costco Wholesale",             "sector": "Consumer Staples",  "price": 780.20,  "vol": 0.015},
        "BAC":   {"name": "Bank of America Corp.",        "sector": "Financials",        "price": 39.80,   "vol": 0.018},
        "WFC":   {"name": "Wells Fargo & Company",        "sector": "Financials",        "price": 57.30,   "vol": 0.019},
        "GS":    {"name": "Goldman Sachs Group",          "sector": "Financials",        "price": 462.10,  "vol": 0.020},
        "MS":    {"name": "Morgan Stanley",               "sector": "Financials",        "price": 101.40,  "vol": 0.018},
        "AVGO":  {"name": "Broadcom Inc.",                "sector": "Technology",        "price": 1478.50, "vol": 0.028},
        "ORCL":  {"name": "Oracle Corporation",           "sector": "Technology",        "price": 142.80,  "vol": 0.020},
        "CSCO":  {"name": "Cisco Systems Inc.",           "sector": "Technology",        "price": 47.60,   "vol": 0.014},
        "IBM":   {"name": "IBM Corporation",              "sector": "Technology",        "price": 186.30,  "vol": 0.016},
        "INTC":  {"name": "Intel Corporation",            "sector": "Technology",        "price": 31.20,   "vol": 0.025},
        "AMD":   {"name": "Advanced Micro Devices",       "sector": "Technology",        "price": 162.40,  "vol": 0.035},
        "QCOM":  {"name": "Qualcomm Inc.",                "sector": "Technology",        "price": 198.70,  "vol": 0.022},
        "TXN":   {"name": "Texas Instruments",            "sector": "Technology",        "price": 178.50,  "vol": 0.016},
        "NOW":   {"name": "ServiceNow Inc.",              "sector": "Technology",        "price": 798.30,  "vol": 0.025},
        "CRM":   {"name": "Salesforce Inc.",              "sector": "Technology",        "price": 262.40,  "vol": 0.023},
        "ADBE":  {"name": "Adobe Inc.",                   "sector": "Technology",        "price": 468.90,  "vol": 0.022},
        "NFLX":  {"name": "Netflix Inc.",                 "sector": "Communication",     "price": 682.30,  "vol": 0.028},
        "DIS":   {"name": "The Walt Disney Company",      "sector": "Communication",     "price": 98.40,   "vol": 0.020},
        "WMT":   {"name": "Walmart Inc.",                 "sector": "Consumer Staples",  "price": 68.40,   "vol": 0.012},
        "NKE":   {"name": "Nike Inc.",                    "sector": "Consumer Discret.", "price": 87.30,   "vol": 0.018},
        "MCD":   {"name": "McDonald's Corporation",       "sector": "Consumer Discret.", "price": 282.60,  "vol": 0.012},
        "SBUX":  {"name": "Starbucks Corporation",        "sector": "Consumer Discret.", "price": 79.40,   "vol": 0.018},
        "BA":    {"name": "Boeing Company",               "sector": "Industrials",       "price": 178.50,  "vol": 0.030},
        "CAT":   {"name": "Caterpillar Inc.",              "sector": "Industrials",       "price": 348.90,  "vol": 0.018},
        "GE":    {"name": "GE Aerospace",                 "sector": "Industrials",       "price": 162.40,  "vol": 0.022},
        "HON":   {"name": "Honeywell International",      "sector": "Industrials",       "price": 198.30,  "vol": 0.015},
        "UPS":   {"name": "United Parcel Service",        "sector": "Industrials",       "price": 132.80,  "vol": 0.016},
        "LMT":   {"name": "Lockheed Martin",              "sector": "Industrials",       "price": 472.80,  "vol": 0.014},
        "NEE":   {"name": "NextEra Energy Inc.",          "sector": "Utilities",         "price": 74.20,   "vol": 0.016},
        "AMT":   {"name": "American Tower Corp.",         "sector": "Real Estate",       "price": 198.60,  "vol": 0.018},
        "FCX":   {"name": "Freeport-McMoRan Inc.",        "sector": "Materials",         "price": 48.30,   "vol": 0.028},
        "LIN":   {"name": "Linde plc",                    "sector": "Materials",         "price": 448.90,  "vol": 0.014},
        "COP":   {"name": "ConocoPhillips",               "sector": "Energy",            "price": 118.70,  "vol": 0.020},
        "PFE":   {"name": "Pfizer Inc.",                  "sector": "Healthcare",        "price": 26.80,   "vol": 0.016},
        "AMGN":  {"name": "Amgen Inc.",                   "sector": "Healthcare",        "price": 298.40,  "vol": 0.016},
        "BLK":   {"name": "BlackRock Inc.",               "sector": "Financials",        "price": 898.40,  "vol": 0.016},
        "AXP":   {"name": "American Express Company",     "sector": "Financials",        "price": 228.70,  "vol": 0.017},
        "SPGI":  {"name": "S&P Global Inc.",              "sector": "Financials",        "price": 482.60,  "vol": 0.015},
        "CME":   {"name": "CME Group Inc.",               "sector": "Financials",        "price": 212.40,  "vol": 0.014},
        "PYPL":  {"name": "PayPal Holdings Inc.",         "sector": "Financials",        "price": 64.80,   "vol": 0.028},
        "UBER":  {"name": "Uber Technologies Inc.",       "sector": "Technology",        "price": 72.40,   "vol": 0.030},
        "NFLXH": {"name": "Netflix Holdings",             "sector": "Communication",     "price": 682.30,  "vol": 0.025},
        "ABNB":  {"name": "Airbnb Inc.",                  "sector": "Consumer Discret.", "price": 142.30,  "vol": 0.028},
        "COIN":  {"name": "Coinbase Global Inc.",         "sector": "Financials",        "price": 228.40,  "vol": 0.055},
        "SPOT":  {"name": "Spotify Technology",           "sector": "Communication",     "price": 312.80,  "vol": 0.030},
        "SLB":   {"name": "SLB (Schlumberger)",           "sector": "Energy",            "price": 48.20,   "vol": 0.022},
        "DE":    {"name": "Deere & Company",              "sector": "Industrials",       "price": 392.40,  "vol": 0.018},
        "MMM":   {"name": "3M Company",                   "sector": "Industrials",       "price": 94.60,   "vol": 0.020},
        "RTX":   {"name": "RTX Corporation",              "sector": "Industrials",       "price": 112.40,  "vol": 0.015},
        "MDT":   {"name": "Medtronic plc",                "sector": "Healthcare",        "price": 82.30,   "vol": 0.014},
        "ICE":   {"name": "Intercontinental Exchange",    "sector": "Financials",        "price": 148.30,  "vol": 0.015},
        "TGT":   {"name": "Target Corporation",           "sector": "Consumer Discret.", "price": 155.80,  "vol": 0.020},
        "MMC":   {"name": "Marsh & McLennan",             "sector": "Financials",        "price": 198.60,  "vol": 0.013},
        "T":     {"name": "AT&T Inc.",                    "sector": "Communication",     "price": 17.80,   "vol": 0.013},
        "VZ":    {"name": "Verizon Communications",       "sector": "Communication",     "price": 40.20,   "vol": 0.012},
        "DUK":   {"name": "Duke Energy Corporation",      "sector": "Utilities",         "price": 98.30,   "vol": 0.012},
        "SO":    {"name": "Southern Company",             "sector": "Utilities",         "price": 87.40,   "vol": 0.011},
        "OXY":   {"name": "Occidental Petroleum",         "sector": "Energy",            "price": 62.40,   "vol": 0.025},
        "GILD":  {"name": "Gilead Sciences Inc.",         "sector": "Healthcare",        "price": 68.90,   "vol": 0.015},
        "AON":   {"name": "Aon plc",                      "sector": "Financials",        "price": 312.80,  "vol": 0.014},
        "BKNG":  {"name": "Booking Holdings Inc.",        "sector": "Consumer Discret.", "price": 4528.40, "vol": 0.022},
        "REGN":  {"name": "Regeneron Pharmaceuticals",    "sector": "Healthcare",        "price": 1028.40, "vol": 0.022},
        "ISRG":  {"name": "Intuitive Surgical Inc.",      "sector": "Healthcare",        "price": 498.40,  "vol": 0.020},
        "CB":    {"name": "Chubb Limited",                "sector": "Financials",        "price": 268.40,  "vol": 0.014},
        "ETN":   {"name": "Eaton Corporation plc",        "sector": "Industrials",       "price": 328.40,  "vol": 0.016},
        "NSC":   {"name": "Norfolk Southern Corporation", "sector": "Industrials",       "price": 238.40,  "vol": 0.015},
        "WM":    {"name": "Waste Management Inc.",        "sector": "Industrials",       "price": 218.40,  "vol": 0.013},
        "EMR":   {"name": "Emerson Electric Co.",         "sector": "Industrials",       "price": 128.40,  "vol": 0.016},
        "D":     {"name": "Dominion Energy Inc.",         "sector": "Utilities",         "price": 48.40,   "vol": 0.014},
        "EXC":   {"name": "Exelon Corporation",           "sector": "Utilities",         "price": 38.40,   "vol": 0.013},
        "PLD":   {"name": "Prologis Inc.",                "sector": "Real Estate",       "price": 118.40,  "vol": 0.016},
        "SNOW":  {"name": "Snowflake Inc.",               "sector": "Technology",        "price": 148.40,  "vol": 0.038},
        "PLTR":  {"name": "Palantir Technologies Inc.",   "sector": "Technology",        "price": 28.40,   "vol": 0.045},
        "SHOP":  {"name": "Shopify Inc.",                 "sector": "Technology",        "price": 82.40,   "vol": 0.035},
        "ZM":    {"name": "Zoom Video Communications",    "sector": "Technology",        "price": 68.40,   "vol": 0.030},
        "SQ":    {"name": "Block Inc.",                   "sector": "Financials",        "price": 78.40,   "vol": 0.035},
        "ROKU":  {"name": "Roku Inc.",                    "sector": "Technology",        "price": 68.40,   "vol": 0.040},
    },
    "LSE": {
        "SHEL":  {"name": "Shell plc",                    "sector": "Energy",            "price": 27.82,   "vol": 0.016},
        "HSBA":  {"name": "HSBC Holdings plc",            "sector": "Financials",        "price": 7.24,    "vol": 0.014},
        "ULVR":  {"name": "Unilever plc",                 "sector": "Consumer Staples",  "price": 44.18,   "vol": 0.012},
        "AZN":   {"name": "AstraZeneca plc",              "sector": "Healthcare",        "price": 124.50,  "vol": 0.015},
        "BP":    {"name": "BP plc",                       "sector": "Energy",            "price": 4.62,    "vol": 0.018},
        "RIO":   {"name": "Rio Tinto plc",                "sector": "Materials",         "price": 54.82,   "vol": 0.020},
        "LSEG":  {"name": "London Stock Exchange Group",  "sector": "Financials",        "price": 98.46,   "vol": 0.014},
        "GSK":   {"name": "GSK plc",                      "sector": "Healthcare",        "price": 15.82,   "vol": 0.013},
        "BT":    {"name": "BT Group plc",                 "sector": "Communication",     "price": 1.42,    "vol": 0.018},
        "BARC":  {"name": "Barclays plc",                 "sector": "Financials",        "price": 2.28,    "vol": 0.020},
        "LLOY":  {"name": "Lloyds Banking Group",         "sector": "Financials",        "price": 0.58,    "vol": 0.018},
        "NWG":   {"name": "NatWest Group plc",            "sector": "Financials",        "price": 3.48,    "vol": 0.017},
        "STAN":  {"name": "Standard Chartered plc",       "sector": "Financials",        "price": 8.24,    "vol": 0.018},
        "PRU":   {"name": "Prudential plc",               "sector": "Financials",        "price": 9.48,    "vol": 0.018},
        "LGEN":  {"name": "Legal & General Group",        "sector": "Financials",        "price": 2.28,    "vol": 0.016},
        "AV":    {"name": "Aviva plc",                    "sector": "Financials",        "price": 4.82,    "vol": 0.015},
        "DGE":   {"name": "Diageo plc",                   "sector": "Consumer Staples",  "price": 24.82,   "vol": 0.012},
        "BATS":  {"name": "British American Tobacco",     "sector": "Consumer Staples",  "price": 22.46,   "vol": 0.014},
        "IMB":   {"name": "Imperial Brands plc",          "sector": "Consumer Staples",  "price": 18.64,   "vol": 0.013},
        "MKS":   {"name": "Marks & Spencer Group",        "sector": "Consumer Discret.", "price": 3.62,    "vol": 0.022},
        "TSCO":  {"name": "Tesco plc",                    "sector": "Consumer Staples",  "price": 3.84,    "vol": 0.013},
        "SBRY":  {"name": "Sainsbury's (J) plc",          "sector": "Consumer Staples",  "price": 2.82,    "vol": 0.014},
        "WPP":   {"name": "WPP plc",                      "sector": "Communication",     "price": 7.24,    "vol": 0.018},
        "VOD":   {"name": "Vodafone Group plc",           "sector": "Communication",     "price": 0.72,    "vol": 0.016},
        "BA_":   {"name": "BAE Systems plc",              "sector": "Industrials",       "price": 14.82,   "vol": 0.015},
        "RR":    {"name": "Rolls-Royce Holdings",         "sector": "Industrials",       "price": 4.82,    "vol": 0.028},
        "CRH":   {"name": "CRH plc",                      "sector": "Materials",         "price": 68.42,   "vol": 0.018},
        "GLEN":  {"name": "Glencore plc",                 "sector": "Materials",         "price": 4.48,    "vol": 0.022},
        "AAL":   {"name": "Anglo American plc",           "sector": "Materials",         "price": 22.64,   "vol": 0.024},
        "BHP":   {"name": "BHP Group plc",                "sector": "Materials",         "price": 22.84,   "vol": 0.020},
        "ANTO":  {"name": "Antofagasta plc",              "sector": "Materials",         "price": 18.82,   "vol": 0.026},
        "FRES":  {"name": "Fresnillo plc",                "sector": "Materials",         "price": 6.48,    "vol": 0.030},
        "SVT":   {"name": "Severn Trent plc",             "sector": "Utilities",         "price": 28.42,   "vol": 0.011},
        "UU":    {"name": "United Utilities Group",       "sector": "Utilities",         "price": 10.84,   "vol": 0.012},
        "NG":    {"name": "National Grid plc",            "sector": "Utilities",         "price": 9.82,    "vol": 0.012},
        "SSE":   {"name": "SSE plc",                      "sector": "Utilities",         "price": 18.64,   "vol": 0.013},
        "CNA":   {"name": "Centrica plc",                 "sector": "Utilities",         "price": 1.52,    "vol": 0.020},
        "SGE":   {"name": "Sage Group plc",               "sector": "Technology",        "price": 12.82,   "vol": 0.018},
        "AUTO":  {"name": "Auto Trader Group",            "sector": "Technology",        "price": 8.42,    "vol": 0.018},
        "EXPN":  {"name": "Experian plc",                 "sector": "Technology",        "price": 38.42,   "vol": 0.015},
        "REL":   {"name": "RELX plc",                     "sector": "Communication",     "price": 38.82,   "vol": 0.012},
        "PSON":  {"name": "Pearson plc",                  "sector": "Communication",     "price": 12.84,   "vol": 0.014},
        "MNG":   {"name": "M&G plc",                      "sector": "Financials",        "price": 2.24,    "vol": 0.016},
        "ABDN":  {"name": "abrdn plc",                    "sector": "Financials",        "price": 1.62,    "vol": 0.022},
        "ITV":   {"name": "ITV plc",                      "sector": "Communication",     "price": 0.78,    "vol": 0.022},
        "MNDI":  {"name": "Mondi plc",                    "sector": "Materials",         "price": 14.82,   "vol": 0.018},
        "NXT":   {"name": "Next plc",                     "sector": "Consumer Discret.", "price": 98.40,   "vol": 0.016},
        "OCDO":  {"name": "Ocado Group plc",              "sector": "Consumer Discret.", "price": 3.82,    "vol": 0.040},
        "JD_":   {"name": "JD Sports Fashion",            "sector": "Consumer Discret.", "price": 1.28,    "vol": 0.025},
        "DCC":   {"name": "DCC plc",                      "sector": "Energy",            "price": 42.80,   "vol": 0.015},
        "AHT":   {"name": "Ashtead Group plc",            "sector": "Industrials",       "price": 48.24,   "vol": 0.020},
        "CPG":   {"name": "Compass Group plc",            "sector": "Consumer Staples",  "price": 22.42,   "vol": 0.013},
        "BNZL":  {"name": "Bunzl plc",                    "sector": "Industrials",       "price": 32.82,   "vol": 0.014},
        "BRBY":  {"name": "Burberry Group plc",           "sector": "Consumer Discret.", "price": 12.38,   "vol": 0.024},
        "WTB":   {"name": "Whitbread plc",                "sector": "Consumer Discret.", "price": 28.42,   "vol": 0.016},
        "IHG":   {"name": "InterContinental Hotels Group","sector": "Consumer Discret.", "price": 58.24,   "vol": 0.016},
        "FLTR":  {"name": "Flutter Entertainment plc",    "sector": "Consumer Discret.", "price": 142.80,  "vol": 0.028},
        "CRDA":  {"name": "Croda International plc",      "sector": "Materials",         "price": 38.42,   "vol": 0.018},
        "HLMA":  {"name": "Halma plc",                    "sector": "Technology",        "price": 22.42,   "vol": 0.015},
        "IMI":   {"name": "IMI plc",                      "sector": "Industrials",       "price": 18.42,   "vol": 0.016},
        "LAND":  {"name": "Land Securities Group plc",    "sector": "Real Estate",       "price": 6.82,    "vol": 0.015},
        "SGRO":  {"name": "Segro plc",                    "sector": "Real Estate",       "price": 7.42,    "vol": 0.015},
        "PHNX":  {"name": "Phoenix Group Holdings plc",   "sector": "Financials",        "price": 5.28,    "vol": 0.018},
        "HLN":   {"name": "Haleon plc",                   "sector": "Healthcare",        "price": 3.84,    "vol": 0.016},
        "RTO":   {"name": "Rentokil Initial plc",         "sector": "Industrials",       "price": 3.82,    "vol": 0.016},
        "BDEV":  {"name": "Barratt Developments plc",     "sector": "Real Estate",       "price": 4.82,    "vol": 0.022},
        "PSN":   {"name": "Persimmon plc",                "sector": "Real Estate",       "price": 10.48,   "vol": 0.022},
        "TW_":   {"name": "Taylor Wimpey plc",            "sector": "Real Estate",       "price": 1.42,    "vol": 0.022},
        "BLND":  {"name": "British Land Company plc",     "sector": "Real Estate",       "price": 3.82,    "vol": 0.016},
        "EMG":   {"name": "Man Group plc",                "sector": "Financials",        "price": 2.28,    "vol": 0.020},
        "DPH":   {"name": "Diploma plc",                  "sector": "Industrials",       "price": 42.80,   "vol": 0.016},
        "CTEC":  {"name": "ConvaTec Group plc",           "sector": "Healthcare",        "price": 2.24,    "vol": 0.018},
        "SPX":   {"name": "Spirax-Sarco Engineering plc", "sector": "Industrials",       "price": 62.40,   "vol": 0.015},
        "INF":   {"name": "Informa plc",                  "sector": "Communication",     "price": 8.42,    "vol": 0.014},
        "IAG":   {"name": "Intl Consolidated Airlines",   "sector": "Industrials",       "price": 1.84,    "vol": 0.025},
        "EZJ":   {"name": "easyJet plc",                  "sector": "Industrials",       "price": 3.82,    "vol": 0.025},
        "HWDN":  {"name": "Howden Joinery Group plc",     "sector": "Consumer Discret.", "price": 7.42,    "vol": 0.018},
        "DLG":   {"name": "Direct Line Insurance Group",  "sector": "Financials",        "price": 2.28,    "vol": 0.020},
        "SMIN":  {"name": "Smiths Group plc",             "sector": "Industrials",       "price": 18.40,   "vol": 0.015},
        "BKG":   {"name": "Berkeley Group Holdings plc",  "sector": "Real Estate",       "price": 42.60,   "vol": 0.018},
        "HIK":   {"name": "Hikma Pharmaceuticals plc",    "sector": "Healthcare",        "price": 22.40,   "vol": 0.015},
        "ITRK":  {"name": "Intertek Group plc",           "sector": "Industrials",       "price": 42.80,   "vol": 0.013},
        "RMV":   {"name": "Rightmove plc",                "sector": "Technology",        "price": 5.82,    "vol": 0.016},
        "MRO":   {"name": "Melrose Industries plc",       "sector": "Industrials",       "price": 5.24,    "vol": 0.020},
        "KGF":   {"name": "Kingfisher plc",               "sector": "Consumer Discret.", "price": 2.82,    "vol": 0.018},
        "STJ":   {"name": "St James's Place plc",         "sector": "Financials",        "price": 8.40,    "vol": 0.018},
        "UTG":   {"name": "Unite Group plc",              "sector": "Real Estate",       "price": 8.42,    "vol": 0.015},
        "LMP":   {"name": "LondonMetric Property plc",    "sector": "Real Estate",       "price": 1.82,    "vol": 0.014},
        "PNN":   {"name": "Pennon Group plc",             "sector": "Utilities",         "price": 6.24,    "vol": 0.013},
        "SKG":   {"name": "Smurfit Kappa Group plc",      "sector": "Materials",         "price": 42.60,   "vol": 0.016},
        "WEIR":  {"name": "Weir Group plc",               "sector": "Industrials",       "price": 22.80,   "vol": 0.018},
        "HSX":   {"name": "Hiscox Ltd",                   "sector": "Financials",        "price": 12.40,   "vol": 0.016},
        "VCT":   {"name": "Victrex plc",                  "sector": "Materials",         "price": 16.40,   "vol": 0.018},
        "INCH":  {"name": "Inchcape plc",                 "sector": "Consumer Discret.", "price": 6.82,    "vol": 0.016},
        "SAFE":  {"name": "Safestore Holdings plc",       "sector": "Real Estate",       "price": 8.42,    "vol": 0.015},
        "SMT":   {"name": "Scottish Mortgage Inv. Trust", "sector": "Financials",        "price": 8.40,    "vol": 0.022},
        "BEZ":   {"name": "Beazley plc",                  "sector": "Financials",        "price": 6.42,    "vol": 0.018},
        "EDV":   {"name": "Endeavour Mining plc",         "sector": "Materials",         "price": 18.42,   "vol": 0.025},
        "ATST":  {"name": "Alliance Trust plc",           "sector": "Financials",        "price": 12.80,   "vol": 0.016},
        "WIZZ":  {"name": "Wizz Air Holdings plc",        "sector": "Industrials",       "price": 12.40,   "vol": 0.030},
    },
    "HKEX": {
        "TENCENT":  {"name": "Tencent Holdings",          "sector": "Technology",        "price": 358.40,  "vol": 0.025},
        "ALIBABA":  {"name": "Alibaba Group Holding",     "sector": "Technology",        "price": 82.60,   "vol": 0.030},
        "HSBCHK":   {"name": "HSBC Holdings (HK)",        "sector": "Financials",        "price": 60.45,   "vol": 0.013},
        "AIA":      {"name": "AIA Group Limited",         "sector": "Financials",        "price": 52.80,   "vol": 0.015},
        "CNOOC":    {"name": "CNOOC Limited",             "sector": "Energy",            "price": 18.42,   "vol": 0.022},
        "BIDU":     {"name": "Baidu Inc.",                "sector": "Technology",        "price": 94.80,   "vol": 0.030},
        "XIAOMI":   {"name": "Xiaomi Corporation",        "sector": "Technology",        "price": 18.62,   "vol": 0.028},
        "MEITUAN":  {"name": "Meituan",                   "sector": "Technology",        "price": 152.40,  "vol": 0.032},
        "PING":     {"name": "Ping An Insurance",         "sector": "Financials",        "price": 42.60,   "vol": 0.018},
        "BYD":      {"name": "BYD Company Limited",       "sector": "Automotive",        "price": 248.80,  "vol": 0.030},
        "HKEXCO":   {"name": "HKEX Limited",              "sector": "Financials",        "price": 278.40,  "vol": 0.016},
        "CKH":      {"name": "CK Hutchison Holdings",     "sector": "Conglomerate",      "price": 38.40,   "vol": 0.015},
        "CATHAY":   {"name": "Cathay Pacific Airways",    "sector": "Transport",         "price": 8.24,    "vol": 0.025},
        "SUNHUNG":  {"name": "Sun Hung Kai Properties",   "sector": "Real Estate",       "price": 82.40,   "vol": 0.016},
        "CLP":      {"name": "CLP Holdings Limited",      "sector": "Utilities",         "price": 52.40,   "vol": 0.011},
        "MTRHK":    {"name": "MTR Corporation",           "sector": "Transport",         "price": 28.60,   "vol": 0.012},
        "LENOVO":   {"name": "Lenovo Group Limited",      "sector": "Technology",        "price": 8.48,    "vol": 0.022},
        "ZTE":      {"name": "ZTE Corporation",           "sector": "Technology",        "price": 28.40,   "vol": 0.025},
        "CTRIP":    {"name": "Trip.com Group",            "sector": "Consumer Discret.", "price": 48.60,   "vol": 0.028},
        "JD":       {"name": "JD.com Inc.",               "sector": "Consumer Discret.", "price": 28.40,   "vol": 0.032},
        "NIO":      {"name": "NIO Inc.",                  "sector": "Automotive",        "price": 4.82,    "vol": 0.045},
        "NETEASE":  {"name": "NetEase Inc.",               "sector": "Technology",        "price": 148.40,  "vol": 0.024},
        "BILIBILI": {"name": "Bilibili Inc.",             "sector": "Communication",     "price": 14.60,   "vol": 0.038},
        "BOCHK":    {"name": "Bank of China (HK)",        "sector": "Financials",        "price": 24.80,   "vol": 0.013},
        "HANGSENG": {"name": "Hang Seng Bank Limited",    "sector": "Financials",        "price": 98.40,   "vol": 0.012},
        "ICBC":     {"name": "ICBC (HK)",                 "sector": "Financials",        "price": 4.28,    "vol": 0.012},
        "CCB":      {"name": "China Construction Bank",   "sector": "Financials",        "price": 5.48,    "vol": 0.012},
        "CMB":      {"name": "China Merchants Bank",      "sector": "Financials",        "price": 28.60,   "vol": 0.018},
        "CMOBILE":  {"name": "China Mobile Limited",      "sector": "Communication",     "price": 72.40,   "vol": 0.013},
        "SINOPEC":  {"name": "Sinopec Corp.",             "sector": "Energy",            "price": 4.82,    "vol": 0.018},
        "PETROCHINA":{"name": "PetroChina Company",       "sector": "Energy",            "price": 5.42,    "vol": 0.018},
        "NONGFU":   {"name": "Nongfu Spring Co.",         "sector": "Consumer Staples",  "price": 28.40,   "vol": 0.018},
        "MENGNIU":  {"name": "China Mengniu Dairy",       "sector": "Consumer Staples",  "price": 14.60,   "vol": 0.020},
        "KUAISHOU": {"name": "Kuaishou Technology",       "sector": "Technology",        "price": 42.80,   "vol": 0.030},
        "XPEV":     {"name": "XPeng Inc.",                "sector": "Automotive",        "price": 8.24,    "vol": 0.042},
        "LI_AUTO":  {"name": "Li Auto Inc.",              "sector": "Automotive",        "price": 18.60,   "vol": 0.038},
        "SWIRE":    {"name": "Swire Pacific Limited",     "sector": "Conglomerate",      "price": 52.80,   "vol": 0.015},
        "CHOW":     {"name": "Chow Tai Fook Jewellery",   "sector": "Consumer Discret.", "price": 9.24,    "vol": 0.022},
        "CUNICOM":  {"name": "China Unicom (HK)",         "sector": "Communication",     "price": 6.24,    "vol": 0.016},
        "HKE":      {"name": "HK Electric Investments",   "sector": "Utilities",         "price": 7.42,    "vol": 0.010},
        "BOC":      {"name": "Bank of China Limited",     "sector": "Financials",        "price": 2.98,    "vol": 0.013},
        "WEIBO":    {"name": "Weibo Corporation",         "sector": "Communication",     "price": 8.42,    "vol": 0.030},
        "PAX":      {"name": "PAX Global Technology",     "sector": "Technology",        "price": 4.48,    "vol": 0.025},
        "HENDERSON":{"name": "Henderson Land Dev.",       "sector": "Real Estate",       "price": 24.80,   "vol": 0.018},
        "TOWNGAS":  {"name": "Hong Kong & China Gas",     "sector": "Utilities",         "price": 5.24,    "vol": 0.012},
        "DAOHE":    {"name": "Dah Sing Financial",        "sector": "Financials",        "price": 48.60,   "vol": 0.014},
        "WHARF":    {"name": "Wharf Real Estate",         "sector": "Real Estate",       "price": 24.60,   "vol": 0.018},
        "LONGFOR":  {"name": "Longfor Group Holdings",   "sector": "Real Estate",       "price": 8.24,    "vol": 0.025},
        "CRLAND":   {"name": "China Resources Land",     "sector": "Real Estate",       "price": 14.82,   "vol": 0.022},
        "BOCOM":    {"name": "Bank of Communications",   "sector": "Financials",        "price": 4.82,    "vol": 0.014},
        "ABCHK":    {"name": "Agricultural Bank of China","sector": "Financials",       "price": 2.82,    "vol": 0.013},
        "CITIC":    {"name": "CITIC Limited",             "sector": "Conglomerate",      "price": 8.24,    "vol": 0.018},
        "COSCO":    {"name": "COSCO Shipping Holdings",  "sector": "Transport",         "price": 9.82,    "vol": 0.025},
        "CPIC":     {"name": "China Pacific Insurance",  "sector": "Financials",        "price": 14.82,   "vol": 0.018},
        "WHEELOCK": {"name": "Wheelock and Company",     "sector": "Real Estate",       "price": 28.40,   "vol": 0.016},
        "PCCW":     {"name": "PCCW Limited",             "sector": "Communication",     "price": 3.82,    "vol": 0.018},
        "CKHH":     {"name": "CK Infrastructure Holdings","sector": "Utilities",        "price": 42.80,   "vol": 0.013},
        "LINKRST":  {"name": "Link Real Estate Inv. Trust","sector": "Real Estate",     "price": 38.40,   "vol": 0.013},
        "CGAS":     {"name": "China Gas Holdings",       "sector": "Utilities",         "price": 8.24,    "vol": 0.018},
        "SINOLAND": {"name": "Sino Land Company",        "sector": "Real Estate",       "price": 8.42,    "vol": 0.016},
        "GWM":      {"name": "Great Wall Motor Company", "sector": "Automotive",        "price": 9.82,    "vol": 0.030},
        "COLAND":   {"name": "China Overseas Land",      "sector": "Real Estate",       "price": 12.40,   "vol": 0.022},
        "WUXI":     {"name": "WuXi AppTec Co.",          "sector": "Healthcare",        "price": 42.80,   "vol": 0.025},
        "ANTA":     {"name": "ANTA Sports Products",     "sector": "Consumer Discret.", "price": 68.40,   "vol": 0.025},
        "LINING":   {"name": "Li Ning Company Limited",  "sector": "Consumer Discret.", "price": 18.40,   "vol": 0.028},
        "GALXY":    {"name": "Galaxy Entertainment Group","sector": "Consumer Discret.","price": 28.40,   "vol": 0.025},
        "SANDSCK":  {"name": "Sands China Ltd",          "sector": "Consumer Discret.", "price": 14.82,   "vol": 0.028},
        "WYNMAC":   {"name": "Wynn Macau Limited",       "sector": "Consumer Discret.", "price": 5.82,    "vol": 0.030},
        "SJM":      {"name": "SJM Holdings Limited",     "sector": "Consumer Discret.", "price": 3.82,    "vol": 0.030},
        "MGMHK":    {"name": "MGM China Holdings",       "sector": "Consumer Discret.", "price": 4.82,    "vol": 0.030},
        "MELCO":    {"name": "Melco Resorts & Entertainment","sector":"Consumer Discret.","price": 4.82,   "vol": 0.032},
        "CINDA":    {"name": "China Cinda Asset Management","sector": "Financials",     "price": 0.82,    "vol": 0.025},
        "HUANENG":  {"name": "Huaneng Power International","sector": "Utilities",       "price": 3.82,    "vol": 0.020},
        "ZHONGAN":  {"name": "ZhongAn Online P&C Insurance","sector": "Financials",     "price": 12.40,   "vol": 0.030},
        "BUDAPAC":  {"name": "Budweiser Brewing APAC",   "sector": "Consumer Staples",  "price": 8.82,    "vol": 0.018},
        "TINGYI":   {"name": "Tingyi (Cayman Is.) Holding","sector": "Consumer Staples","price": 8.40,    "vol": 0.018},
        "WANTWANT": {"name": "Want Want China Holdings", "sector": "Consumer Staples",  "price": 4.82,    "vol": 0.018},
        "FEIHE":    {"name": "China Feihe Limited",      "sector": "Consumer Staples",  "price": 4.82,    "vol": 0.022},
        "SMOORE":   {"name": "Smoore International Holdings","sector":"Technology",      "price": 8.42,    "vol": 0.030},
        "RAZER":    {"name": "Razer Inc.",               "sector": "Technology",        "price": 1.42,    "vol": 0.035},
        "HAECO":    {"name": "HAECO Holdings Limited",   "sector": "Industrials",       "price": 48.60,   "vol": 0.016},
        "GEELY":    {"name": "Geely Automobile Holdings","sector": "Automotive",        "price": 9.82,    "vol": 0.028},
        "SHENHUA":  {"name": "China Shenhua Energy",     "sector": "Energy",            "price": 28.40,   "vol": 0.018},
        "CHALCO":   {"name": "Aluminum Corp. of China",  "sector": "Materials",         "price": 4.24,    "vol": 0.025},
        "CRCC":     {"name": "China Railway Construction","sector": "Industrials",      "price": 7.82,    "vol": 0.020},
        "SMICOR":   {"name": "SMIC Holdings",            "sector": "Technology",        "price": 22.80,   "vol": 0.030},
        "CRBEER":   {"name": "China Resources Beer",     "sector": "Consumer Staples",  "price": 28.40,   "vol": 0.022},
        "SINOPH":   {"name": "Sinopharm Group Co.",      "sector": "Healthcare",        "price": 18.40,   "vol": 0.020},
        "CIFI":     {"name": "CIFI Holdings Group",      "sector": "Real Estate",       "price": 0.42,    "vol": 0.040},
        "SUNAC":    {"name": "Sunac China Holdings",     "sector": "Real Estate",       "price": 0.82,    "vol": 0.045},
        "DATANG":   {"name": "Datang Intl Power Generation","sector": "Utilities",      "price": 1.24,    "vol": 0.022},
        "CSPC":     {"name": "CSPC Pharmaceutical Group","sector": "Healthcare",        "price": 4.82,    "vol": 0.022},
        "CONCH":    {"name": "Anhui Conch Cement Co.",   "sector": "Materials",         "price": 18.40,   "vol": 0.020},
        "VANKE":    {"name": "China Vanke Co. Ltd.",     "sector": "Real Estate",       "price": 4.82,    "vol": 0.035},
        "DONGFENG": {"name": "Dongfeng Motor Group",     "sector": "Automotive",        "price": 4.82,    "vol": 0.025},
        "CHINATELE":{"name": "China Telecom Corporation","sector": "Communication",     "price": 3.82,    "vol": 0.014},
        "HAIER":    {"name": "Haier Smart Home Co.",     "sector": "Technology",        "price": 14.82,   "vol": 0.022},
        "POWER":    {"name": "Power Assets Holdings",    "sector": "Utilities",         "price": 42.80,   "vol": 0.012},
        "ORIENT":   {"name": "Orient Overseas International","sector": "Transport",     "price": 82.40,   "vol": 0.022},
        "CNOOC_GAS":{"name": "ENN Energy Holdings",      "sector": "Utilities",         "price": 58.40,   "vol": 0.018},
    },
    "TSE": {
        "TOYOTA":    {"name": "Toyota Motor Corporation",  "sector": "Automotive",        "price": 3420.0,  "vol": 0.018},
        "SONY":      {"name": "Sony Group Corporation",    "sector": "Technology",        "price": 12480.0, "vol": 0.020},
        "SOFTBANK":  {"name": "SoftBank Group Corp.",      "sector": "Technology",        "price": 8240.0,  "vol": 0.035},
        "KEYENCE":   {"name": "Keyence Corporation",       "sector": "Technology",        "price": 58400.0, "vol": 0.018},
        "RECRUIT":   {"name": "Recruit Holdings Co.",      "sector": "Technology",        "price": 8620.0,  "vol": 0.020},
        "MUFG":      {"name": "Mitsubishi UFJ Financial",  "sector": "Financials",        "price": 1482.0,  "vol": 0.018},
        "HONDA":     {"name": "Honda Motor Co. Ltd.",      "sector": "Automotive",        "price": 1824.0,  "vol": 0.018},
        "NINTENDO":  {"name": "Nintendo Co. Ltd.",         "sector": "Technology",        "price": 7840.0,  "vol": 0.025},
        "FANUC":     {"name": "Fanuc Corporation",         "sector": "Industrials",       "price": 4280.0,  "vol": 0.018},
        "CANON":     {"name": "Canon Inc.",                "sector": "Technology",        "price": 4280.0,  "vol": 0.014},
        "FAST":      {"name": "Fast Retailing (Uniqlo)",   "sector": "Consumer Discret.", "price": 42800.0, "vol": 0.022},
        "KDDI":      {"name": "KDDI Corporation",          "sector": "Communication",     "price": 4820.0,  "vol": 0.012},
        "NTT":       {"name": "Nippon Telegraph & Tel.",   "sector": "Communication",     "price": 158.0,   "vol": 0.011},
        "PANASONIC": {"name": "Panasonic Holdings",        "sector": "Technology",        "price": 1248.0,  "vol": 0.020},
        "HITACHI":   {"name": "Hitachi Ltd.",              "sector": "Industrials",       "price": 12480.0, "vol": 0.018},
        "FUJITSU":   {"name": "Fujitsu Limited",           "sector": "Technology",        "price": 24800.0, "vol": 0.018},
        "MURATA":    {"name": "Murata Manufacturing",      "sector": "Technology",        "price": 2480.0,  "vol": 0.022},
        "SHIN_ETSU": {"name": "Shin-Etsu Chemical",        "sector": "Materials",         "price": 5480.0,  "vol": 0.016},
        "DAIKIN":    {"name": "Daikin Industries",         "sector": "Industrials",       "price": 18400.0, "vol": 0.016},
        "KOMATSU":   {"name": "Komatsu Ltd.",              "sector": "Industrials",       "price": 4280.0,  "vol": 0.018},
        "SUZUKI":    {"name": "Suzuki Motor Corporation",  "sector": "Automotive",        "price": 1820.0,  "vol": 0.018},
        "SUBARU":    {"name": "Subaru Corporation",        "sector": "Automotive",        "price": 2840.0,  "vol": 0.018},
        "MAZDA":     {"name": "Mazda Motor Corporation",   "sector": "Automotive",        "price": 1248.0,  "vol": 0.020},
        "NISSAN":    {"name": "Nissan Motor Co. Ltd.",     "sector": "Automotive",        "price": 582.0,   "vol": 0.025},
        "MITSUI":    {"name": "Mitsui & Co. Ltd.",         "sector": "Conglomerate",      "price": 2840.0,  "vol": 0.018},
        "ITOCHU":    {"name": "ITOCHU Corporation",        "sector": "Conglomerate",      "price": 7840.0,  "vol": 0.016},
        "SUMITOMO":  {"name": "Sumitomo Corporation",      "sector": "Conglomerate",      "price": 3480.0,  "vol": 0.017},
        "MARUBENI":  {"name": "Marubeni Corporation",      "sector": "Conglomerate",      "price": 2240.0,  "vol": 0.018},
        "ASAHI":     {"name": "Asahi Group Holdings",      "sector": "Consumer Staples",  "price": 2480.0,  "vol": 0.014},
        "KIRIN":     {"name": "Kirin Holdings Company",    "sector": "Consumer Staples",  "price": 1840.0,  "vol": 0.013},
        "AJINOMOTO": {"name": "Ajinomoto Co. Inc.",        "sector": "Consumer Staples",  "price": 4820.0,  "vol": 0.014},
        "SHISEIDO":  {"name": "Shiseido Company Ltd.",     "sector": "Consumer Staples",  "price": 2480.0,  "vol": 0.016},
        "NOMURA":    {"name": "Nomura Holdings Inc.",      "sector": "Financials",        "price": 758.0,   "vol": 0.022},
        "DAIWA":     {"name": "Daiwa Securities Group",    "sector": "Financials",        "price": 1082.0,  "vol": 0.022},
        "SMFG":      {"name": "Sumitomo Mitsui Financial", "sector": "Financials",        "price": 1248.0,  "vol": 0.018},
        "MIZUHO":    {"name": "Mizuho Financial Group",    "sector": "Financials",        "price": 2840.0,  "vol": 0.018},
        "TOKIO":     {"name": "Tokio Marine Holdings",     "sector": "Financials",        "price": 4280.0,  "vol": 0.014},
        "ORIX":      {"name": "ORIX Corporation",          "sector": "Financials",        "price": 2820.0,  "vol": 0.016},
        "RESONA":    {"name": "Resona Holdings Inc.",      "sector": "Financials",        "price": 1024.0,  "vol": 0.017},
        "SHIMANO":   {"name": "Shimano Inc.",              "sector": "Consumer Discret.", "price": 24800.0, "vol": 0.016},
        "TDK":       {"name": "TDK Corporation",           "sector": "Technology",        "price": 1840.0,  "vol": 0.020},
        "KYOCERA":   {"name": "Kyocera Corporation",       "sector": "Technology",        "price": 1648.0,  "vol": 0.015},
        "NEC":       {"name": "NEC Corporation",           "sector": "Technology",        "price": 12400.0, "vol": 0.020},
        "EBARA":     {"name": "Ebara Corporation",         "sector": "Industrials",       "price": 2840.0,  "vol": 0.020},
        "ROHM":      {"name": "ROHM Co. Ltd.",             "sector": "Technology",        "price": 1820.0,  "vol": 0.018},
        "SOFTBANKM": {"name": "SoftBank Corp. (Mobile)",   "sector": "Communication",     "price": 1842.0,  "vol": 0.015},
        "MS_AD":     {"name": "MS&AD Insurance Group",     "sector": "Financials",        "price": 2840.0,  "vol": 0.014},
        "SOMPO":     {"name": "Sompo Holdings Inc.",       "sector": "Financials",        "price": 3820.0,  "vol": 0.015},
        "OLYMPUS":   {"name": "Olympus Corporation",       "sector": "Healthcare",        "price": 1820.0,  "vol": 0.018},
        "FUJIFILM":  {"name": "Fujifilm Holdings Corp.",   "sector": "Technology",        "price": 2840.0,  "vol": 0.016},
        "RICOH":     {"name": "Ricoh Company Ltd.",        "sector": "Technology",        "price": 1428.0,  "vol": 0.018},
        "SECOM":     {"name": "Secom Co. Ltd.",            "sector": "Industrials",       "price": 8400.0,  "vol": 0.014},
        "NIDEC":     {"name": "Nidec Corporation",         "sector": "Technology",        "price": 4280.0,  "vol": 0.022},
        "TORAY":     {"name": "Toray Industries Inc.",     "sector": "Materials",         "price": 1024.0,  "vol": 0.016},
        "ASAHI_K":   {"name": "Asahi Kasei Corporation",   "sector": "Materials",         "price": 1024.0,  "vol": 0.016},
        "KUBOTA":    {"name": "Kubota Corporation",        "sector": "Industrials",       "price": 2482.0,  "vol": 0.016},
        "MITSUBISHI":{"name": "Mitsubishi Corporation",    "sector": "Conglomerate",      "price": 3420.0,  "vol": 0.018},
        "MIT_ELEC":  {"name": "Mitsubishi Electric Corp.", "sector": "Industrials",       "price": 2480.0,  "vol": 0.016},
        "DENSO":     {"name": "Denso Corporation",         "sector": "Automotive",        "price": 3280.0,  "vol": 0.018},
        "AISIN":     {"name": "Aisin Corporation",         "sector": "Automotive",        "price": 4820.0,  "vol": 0.018},
        "YOKOGAWA":  {"name": "Yokogawa Electric Corp.",   "sector": "Technology",        "price": 2480.0,  "vol": 0.018},
        "DAIFUKU":   {"name": "Daifuku Co. Ltd.",          "sector": "Industrials",       "price": 4280.0,  "vol": 0.018},
        "DISCO":     {"name": "Disco Corporation",         "sector": "Technology",        "price": 48200.0, "vol": 0.025},
        "LASERTEC":  {"name": "Lasertec Corporation",      "sector": "Technology",        "price": 42800.0, "vol": 0.035},
        "SMC_CORP":  {"name": "SMC Corporation",           "sector": "Industrials",       "price": 58400.0, "vol": 0.016},
        "HOYA":      {"name": "Hoya Corporation",          "sector": "Healthcare",        "price": 18400.0, "vol": 0.018},
        "SYSMEX":    {"name": "Sysmex Corporation",        "sector": "Healthcare",        "price": 8420.0,  "vol": 0.020},
        "EISAI":     {"name": "Eisai Co. Ltd.",            "sector": "Healthcare",        "price": 5820.0,  "vol": 0.020},
        "TAKEDA":    {"name": "Takeda Pharmaceutical Co.", "sector": "Healthcare",        "price": 3820.0,  "vol": 0.016},
        "ASTELLAS":  {"name": "Astellas Pharma Inc.",      "sector": "Healthcare",        "price": 1820.0,  "vol": 0.016},
        "DAIICHI":   {"name": "Daiichi Sankyo Co. Ltd.",   "sector": "Healthcare",        "price": 4820.0,  "vol": 0.022},
        "NSC_STEEL": {"name": "Nippon Steel Corporation",  "sector": "Materials",         "price": 3820.0,  "vol": 0.022},
        "JFE":       {"name": "JFE Holdings Inc.",         "sector": "Materials",         "price": 2480.0,  "vol": 0.022},
        "KOITO":     {"name": "Koito Manufacturing Co.",   "sector": "Industrials",       "price": 2480.0,  "vol": 0.020},
        "MAKITA":    {"name": "Makita Corporation",        "sector": "Industrials",       "price": 3820.0,  "vol": 0.018},
        "AMADA":     {"name": "Amada Holdings Co. Ltd.",   "sector": "Industrials",       "price": 1480.0,  "vol": 0.018},
        "THK":       {"name": "THK Co. Ltd.",              "sector": "Industrials",       "price": 2480.0,  "vol": 0.020},
        "ISUZU":     {"name": "Isuzu Motors Limited",      "sector": "Automotive",        "price": 2480.0,  "vol": 0.018},
        "KAWASAKI":  {"name": "Kawasaki Heavy Industries", "sector": "Industrials",       "price": 4280.0,  "vol": 0.022},
        "NIPPON_EX": {"name": "Nippon Express Holdings",   "sector": "Transport",         "price": 2480.0,  "vol": 0.016},
        "YAMATO":    {"name": "Yamato Holdings Co.",       "sector": "Transport",         "price": 2480.0,  "vol": 0.016},
        "SG_HLD":    {"name": "SG Holdings Co. Ltd.",      "sector": "Transport",         "price": 1482.0,  "vol": 0.016},
        "ANA":       {"name": "ANA Holdings Inc.",         "sector": "Transport",         "price": 2820.0,  "vol": 0.022},
        "JAL":       {"name": "Japan Airlines Co.",        "sector": "Transport",         "price": 2980.0,  "vol": 0.022},
        "RYOHIN":    {"name": "Ryohin Keikaku Co. (MUJI)", "sector": "Consumer Discret.", "price": 2480.0,  "vol": 0.020},
        "NITORI":    {"name": "Nitori Holdings Co.",       "sector": "Consumer Discret.", "price": 12480.0, "vol": 0.018},
        "YAMAHA":    {"name": "Yamaha Corporation",        "sector": "Consumer Discret.", "price": 3420.0,  "vol": 0.018},
        "YAMAHA_M":  {"name": "Yamaha Motor Co. Ltd.",     "sector": "Automotive",        "price": 1420.0,  "vol": 0.020},
        "SUNTORY":   {"name": "Suntory Beverage & Food",   "sector": "Consumer Staples",  "price": 4820.0,  "vol": 0.014},
        "MEIJI":     {"name": "Meiji Holdings Co. Ltd.",   "sector": "Consumer Staples",  "price": 2480.0,  "vol": 0.013},
        "YAKULT":    {"name": "Yakult Honsha Co. Ltd.",    "sector": "Consumer Staples",  "price": 2482.0,  "vol": 0.014},
        "NPH":       {"name": "Nippon Paint Holdings",     "sector": "Materials",         "price": 1480.0,  "vol": 0.016},
        "TOTO":      {"name": "TOTO Ltd.",                 "sector": "Industrials",       "price": 4280.0,  "vol": 0.016},
        "JSR":       {"name": "JSR Corporation",           "sector": "Materials",         "price": 4580.0,  "vol": 0.018},
        "HANKYU":    {"name": "Hankyu Hanshin Holdings",   "sector": "Transport",         "price": 1820.0,  "vol": 0.014},
        "TOKYU":     {"name": "Tokyu Corporation",         "sector": "Real Estate",       "price": 1820.0,  "vol": 0.015},
        "SEGA":      {"name": "Sega Sammy Holdings",       "sector": "Technology",        "price": 2480.0,  "vol": 0.022},
        "CAPCOM":    {"name": "Capcom Co. Ltd.",           "sector": "Technology",        "price": 3420.0,  "vol": 0.025},
        "SQUARE_EN": {"name": "Square Enix Holdings",      "sector": "Technology",        "price": 5820.0,  "vol": 0.022},
        "KDDI_OW":   {"name": "Otsuka Holdings Co.",      "sector": "Healthcare",        "price": 4820.0,  "vol": 0.016},
    },

    # ── SSE — Shanghai Stock Exchange (CNY) ──────────────────────────────────
    "SSE": {
        "ICBC_A":      {"name": "ICBC (A Share)",                  "sector": "Financials",        "price": 5.82,    "vol": 0.012},
        "CCB_A":       {"name": "China Construction Bank (A)",     "sector": "Financials",        "price": 6.48,    "vol": 0.012},
        "BOC_A":       {"name": "Bank of China (A Share)",         "sector": "Financials",        "price": 4.82,    "vol": 0.012},
        "PINGAN":      {"name": "Ping An Insurance (A)",           "sector": "Financials",        "price": 42.60,   "vol": 0.018},
        "SINOPEC_A":   {"name": "Sinopec Corp. (A Share)",         "sector": "Energy",            "price": 6.82,    "vol": 0.018},
        "PETROCHINA_A":{"name": "PetroChina (A Share)",            "sector": "Energy",            "price": 8.42,    "vol": 0.018},
        "CNOOC_A":     {"name": "CNOOC Limited (A Share)",         "sector": "Energy",            "price": 18.42,   "vol": 0.020},
        "CMOBILE_A":   {"name": "China Mobile (A Share)",          "sector": "Communication",     "price": 72.40,   "vol": 0.013},
        "BAOSHAN":     {"name": "Baoshan Iron & Steel",            "sector": "Materials",         "price": 6.82,    "vol": 0.022},
        "WANHUA":      {"name": "Wanhua Chemical Group",           "sector": "Materials",         "price": 82.40,   "vol": 0.022},
        "PACC":        {"name": "PICC Property & Casualty (A)",    "sector": "Financials",        "price": 12.40,   "vol": 0.016},
        "BOCOM_A":     {"name": "Bank of Communications (A)",      "sector": "Financials",        "price": 6.82,    "vol": 0.014},
        "CMB_A":       {"name": "China Merchants Bank (A)",        "sector": "Financials",        "price": 28.60,   "vol": 0.018},
        "SPDB":        {"name": "Shanghai Pudong Dev. Bank",       "sector": "Financials",        "price": 9.82,    "vol": 0.015},
        "CITIC_A":     {"name": "CITIC Securities (A)",            "sector": "Financials",        "price": 18.40,   "vol": 0.025},
        "HAITONG":     {"name": "Haitong Securities",              "sector": "Financials",        "price": 8.42,    "vol": 0.025},
        "SHENERGY":    {"name": "Shenergy Company",                "sector": "Utilities",         "price": 8.82,    "vol": 0.015},
        "HUANENGSUE":  {"name": "Huaneng Power International (A)", "sector": "Utilities",         "price": 6.82,    "vol": 0.018},
        "BAOSTEEL":    {"name": "Baowu Steel Group",               "sector": "Materials",         "price": 7.82,    "vol": 0.022},
        "CHALCO_A":    {"name": "Aluminum Corp. of China (A)",     "sector": "Materials",         "price": 5.82,    "vol": 0.022},
        "CRRC_A":      {"name": "CRRC Corporation (A Share)",      "sector": "Industrials",       "price": 6.42,    "vol": 0.018},
        "AVIC":        {"name": "AVIC Aviation Industy (A)",       "sector": "Industrials",       "price": 12.40,   "vol": 0.020},
        "COSCO_A":     {"name": "COSCO Shipping Holdings (A)",     "sector": "Transport",         "price": 12.80,   "vol": 0.025},
        "YANGZIJIANG": {"name": "Yangzijiang Shipbuilding",        "sector": "Industrials",       "price": 18.40,   "vol": 0.022},
        "CR_LAND_A":   {"name": "China Resources Land (A)",        "sector": "Real Estate",       "price": 14.82,   "vol": 0.020},
        "POLY_RE":     {"name": "Poly Developments & Holdings",    "sector": "Real Estate",       "price": 8.82,    "vol": 0.022},
        "GREENLAND":   {"name": "Greenland Holdings Corp.",        "sector": "Real Estate",       "price": 2.82,    "vol": 0.030},
        "LONGFOR_A":   {"name": "Longfor Group Holdings (A)",      "sector": "Real Estate",       "price": 8.24,    "vol": 0.025},
        "ANHUI_CONCH": {"name": "Anhui Conch Cement (A)",          "sector": "Materials",         "price": 22.40,   "vol": 0.020},
        "CHINA_CST":   {"name": "China State Construction (A)",    "sector": "Industrials",       "price": 8.42,    "vol": 0.018},
        "SHENZHEN_AIR":{"name": "Shenzhen Airport Co.",            "sector": "Transport",         "price": 6.82,    "vol": 0.018},
        "SHANGHAI_AIR":{"name": "Shanghai International Airport",  "sector": "Transport",         "price": 42.80,   "vol": 0.018},
        "GUANGSHEN":   {"name": "Guangshen Railway",               "sector": "Transport",         "price": 2.82,    "vol": 0.016},
        "SAIC_A":      {"name": "SAIC Motor Corporation (A)",      "sector": "Automotive",        "price": 14.82,   "vol": 0.022},
        "CHANGAN_A":   {"name": "Chongqing Changan Auto (A)",      "sector": "Automotive",        "price": 12.40,   "vol": 0.025},
        "FAWCAR":      {"name": "FAW Car Co. Ltd.",                "sector": "Automotive",        "price": 8.42,    "vol": 0.025},
        "YILI":        {"name": "Inner Mongolia Yili Industrial",  "sector": "Consumer Staples",  "price": 24.80,   "vol": 0.018},
        "MOUTAI":      {"name": "Kweichow Moutai Co. Ltd.",        "sector": "Consumer Staples",  "price": 1580.0,  "vol": 0.020},
        "WULIANGYE":   {"name": "Wuliangye Yibin Co. Ltd.",        "sector": "Consumer Staples",  "price": 128.0,   "vol": 0.022},
        "LUZHOU":      {"name": "Luzhou Laojiao Co. Ltd.",         "sector": "Consumer Staples",  "price": 78.40,   "vol": 0.022},
        "SHUANGHUI":   {"name": "Shuanghui Development",          "sector": "Consumer Staples",  "price": 18.40,   "vol": 0.016},
        "GREE_A":      {"name": "Gree Electric (A Share)",         "sector": "Industrials",       "price": 28.80,   "vol": 0.022},
        "MIDEA_A":     {"name": "Midea Group (A Share)",           "sector": "Industrials",       "price": 48.60,   "vol": 0.020},
        "HAIER_A":     {"name": "Haier Smart Home (A Share)",      "sector": "Technology",        "price": 24.80,   "vol": 0.020},
        "HKIA_A":      {"name": "China CSSC Holdings",             "sector": "Industrials",       "price": 12.40,   "vol": 0.022},
        "SHIMAO":      {"name": "Shimao Group Holdings",           "sector": "Real Estate",       "price": 0.82,    "vol": 0.045},
        "CRCHEM":      {"name": "China Resources Chemical",        "sector": "Materials",         "price": 12.40,   "vol": 0.022},
        "HENGLI":      {"name": "Hengli Petrochemical Co.",        "sector": "Materials",         "price": 14.80,   "vol": 0.022},
        "RONGSHENG":   {"name": "Rongsheng Petrochemical",         "sector": "Materials",         "price": 8.42,    "vol": 0.025},
        "CNMED":       {"name": "China National Medicines",        "sector": "Healthcare",        "price": 24.80,   "vol": 0.018},
    },

    # ── SZSE — Shenzhen Stock Exchange (CNY) ─────────────────────────────────
    "SZSE": {
        "BYD_A":       {"name": "BYD Co. Ltd. (A Share)",          "sector": "Automotive",        "price": 248.80,  "vol": 0.030},
        "CATL":        {"name": "CATL (Contemporary Amperex)",      "sector": "Technology",        "price": 198.40,  "vol": 0.032},
        "HIKVISION":   {"name": "Hikvision Digital Technology",    "sector": "Technology",        "price": 28.40,   "vol": 0.025},
        "GREE_SZ":     {"name": "Gree Electric Appliances",        "sector": "Industrials",       "price": 28.80,   "vol": 0.022},
        "MIDEA_SZ":    {"name": "Midea Group Co. Ltd.",            "sector": "Industrials",       "price": 48.60,   "vol": 0.020},
        "SMIC_A":      {"name": "SMIC (A Share)",                  "sector": "Technology",        "price": 48.80,   "vol": 0.030},
        "ZTE_A":       {"name": "ZTE Corporation (A Share)",       "sector": "Technology",        "price": 28.40,   "vol": 0.025},
        "LUXSHARE":    {"name": "Luxshare Precision Industry",     "sector": "Technology",        "price": 24.80,   "vol": 0.028},
        "MINDRAY":     {"name": "Mindray Medical International",   "sector": "Healthcare",        "price": 248.80,  "vol": 0.022},
        "SANGFOR":     {"name": "Sangfor Technologies Inc.",       "sector": "Technology",        "price": 82.40,   "vol": 0.030},
        "TRANSSION":   {"name": "Transsion Holdings",              "sector": "Technology",        "price": 68.40,   "vol": 0.028},
        "DAHUA_TECH":  {"name": "Dahua Technology Co. Ltd.",       "sector": "Technology",        "price": 14.82,   "vol": 0.025},
        "WUXI_BIO":    {"name": "WuXi Biologics",                  "sector": "Healthcare",        "price": 18.40,   "vol": 0.030},
        "HENGRUI":     {"name": "Jiangsu Hengrui Medicine",        "sector": "Healthcare",        "price": 28.40,   "vol": 0.025},
        "ZHIFEI_BIO":  {"name": "Zhifei Biological Products",      "sector": "Healthcare",        "price": 48.40,   "vol": 0.025},
        "MWKJ":        {"name": "Muyuan Foodstuff Co. Ltd.",       "sector": "Consumer Staples",  "price": 38.40,   "vol": 0.025},
        "WENS":        {"name": "Wens Foodstuff Group",            "sector": "Consumer Staples",  "price": 14.82,   "vol": 0.025},
        "NEW_HOPE":    {"name": "New Hope Liuhe Co. Ltd.",         "sector": "Consumer Staples",  "price": 8.82,    "vol": 0.025},
        "PING_AN_HLT": {"name": "Ping An Healthcare",             "sector": "Healthcare",        "price": 14.82,   "vol": 0.028},
        "MAANSHAN":    {"name": "Maanshan Iron & Steel",           "sector": "Materials",         "price": 2.82,    "vol": 0.025},
        "GUANGHAO":    {"name": "Guang Dong HEC Technology",       "sector": "Technology",        "price": 18.40,   "vol": 0.028},
        "O2MICRO":     {"name": "CITIC Guoan Information",         "sector": "Technology",        "price": 4.82,    "vol": 0.030},
        "TRINA_SOLAR": {"name": "Trina Solar Co. Ltd.",            "sector": "Energy",            "price": 8.42,    "vol": 0.035},
        "LONGi_GRN":   {"name": "LONGi Green Energy Technology",   "sector": "Energy",            "price": 18.40,   "vol": 0.032},
        "JA_SOLAR":    {"name": "JA Solar Technology",             "sector": "Energy",            "price": 14.80,   "vol": 0.035},
        "SUNGROW":     {"name": "Sungrow Power Supply Co.",        "sector": "Energy",            "price": 68.40,   "vol": 0.030},
        "NAURA_TECH":  {"name": "NAURA Technology Group",          "sector": "Technology",        "price": 98.40,   "vol": 0.030},
        "ACRM":        {"name": "Advanced Micro-Fabrication Equip",  "sector": "Technology",      "price": 248.0,   "vol": 0.035},
        "CAMBRICON":   {"name": "Cambricon Technologies",          "sector": "Technology",        "price": 48.80,   "vol": 0.045},
        "UNISPLEND":   {"name": "UniSplendour Corporation",        "sector": "Technology",        "price": 28.40,   "vol": 0.025},
        "CGUARD":      {"name": "China Greatwall Technology",      "sector": "Technology",        "price": 8.82,    "vol": 0.030},
        "OMNIVISION":  {"name": "Will Semiconductor Shanghai",     "sector": "Technology",        "price": 48.40,   "vol": 0.032},
        "SILAN_MICRO": {"name": "Hangzhou Silan Microelectronics", "sector": "Technology",        "price": 14.80,   "vol": 0.028},
        "TONGWEI":     {"name": "Tongwei Co. Ltd.",                "sector": "Energy",            "price": 12.80,   "vol": 0.030},
        "DAQO_NEW":    {"name": "Daqo New Energy (A)",             "sector": "Energy",            "price": 28.40,   "vol": 0.035},
        "SHENGHE":     {"name": "Shenghe Resources",               "sector": "Materials",         "price": 8.82,    "vol": 0.028},
        "EVE_ENERGY":  {"name": "EVE Energy Co. Ltd.",             "sector": "Technology",        "price": 28.40,   "vol": 0.030},
        "LISHEN":      {"name": "Tianjin Lishen Battery",          "sector": "Technology",        "price": 24.80,   "vol": 0.028},
        "NORTHLI":     {"name": "BTR New Material Group",          "sector": "Materials",         "price": 18.40,   "vol": 0.030},
        "CAMEL":       {"name": "Camel Group Co. Ltd.",            "sector": "Technology",        "price": 8.82,    "vol": 0.022},
        "XGIMI_TECH":  {"name": "XGIMI Technology Co. Ltd.",       "sector": "Technology",        "price": 48.40,   "vol": 0.035},
        "YEALINK":     {"name": "Yealink Network Technology",      "sector": "Technology",        "price": 48.80,   "vol": 0.025},
        "ZHANGMEN":    {"name": "Zhangmen Education Group",        "sector": "Communication",     "price": 1.82,    "vol": 0.040},
        "SHFDM_SEMI":  {"name": "Shanghai Fullhan Microelectronics","sector": "Technology",       "price": 68.40,   "vol": 0.030},
        "3SBIO":       {"name": "3SBio Inc.",                      "sector": "Healthcare",        "price": 4.82,    "vol": 0.025},
        "CSPC_A":      {"name": "CSPC Pharmaceutical (A Share)",   "sector": "Healthcare",        "price": 6.82,    "vol": 0.022},
        "ZHEJIANG_MT": {"name": "Zhejiang Medicine Co. Ltd.",      "sector": "Healthcare",        "price": 24.80,   "vol": 0.020},
        "SOFARSOLAR":  {"name": "Sofar Solar Co. Ltd.",            "sector": "Energy",            "price": 28.40,   "vol": 0.030},
        "GINLONG":     {"name": "Ginlong Technologies",            "sector": "Energy",            "price": 48.40,   "vol": 0.032},
        "DEYE":        {"name": "Zhejiang Deye Technology",        "sector": "Industrials",       "price": 68.40,   "vol": 0.030},
    },

    # ── TADAWUL — Saudi Exchange (SAR) ───────────────────────────────────────
    "TADAWUL": {
        "ARAMCO":      {"name": "Saudi Aramco",                    "sector": "Energy",            "price": 28.40,   "vol": 0.014},
        "SNB":         {"name": "Saudi National Bank",             "sector": "Financials",        "price": 28.60,   "vol": 0.016},
        "ALINMA":      {"name": "Alinma Bank",                     "sector": "Financials",        "price": 24.80,   "vol": 0.018},
        "RAJHI":       {"name": "Al Rajhi Bank",                   "sector": "Financials",        "price": 82.40,   "vol": 0.015},
        "SABIC":       {"name": "SABIC (Saudi Basic Industries)",  "sector": "Materials",         "price": 68.40,   "vol": 0.016},
        "STC":         {"name": "Saudi Telecom Company",           "sector": "Communication",     "price": 42.80,   "vol": 0.014},
        "RIYAD":       {"name": "Riyad Bank",                      "sector": "Financials",        "price": 18.40,   "vol": 0.017},
        "NCB":         {"name": "National Commercial Bank",        "sector": "Financials",        "price": 28.40,   "vol": 0.015},
        "MAADEN":      {"name": "Saudi Arabian Mining (Ma'aden)",  "sector": "Materials",         "price": 48.80,   "vol": 0.022},
        "SABIC_AGRI":  {"name": "SABIC Agri-Nutrients Co.",        "sector": "Materials",         "price": 98.40,   "vol": 0.018},
        "STCPAY":      {"name": "STC Pay / stc bank",              "sector": "Financials",        "price": 18.40,   "vol": 0.022},
        "BANK_ALBILAD":{"name": "Bank Albilad",                    "sector": "Financials",        "price": 28.80,   "vol": 0.018},
        "BANK_ALJAZIRA":{"name": "Bank AlJazira",                  "sector": "Financials",        "price": 18.40,   "vol": 0.018},
        "SABB":        {"name": "Saudi British Bank (SABB)",       "sector": "Financials",        "price": 28.40,   "vol": 0.016},
        "ARAB_NATGAS": {"name": "Arabian Gas & Power",             "sector": "Energy",            "price": 42.80,   "vol": 0.020},
        "SAUDI_ELEC":  {"name": "Saudi Electricity Company",       "sector": "Utilities",         "price": 18.40,   "vol": 0.014},
        "ACWA_POWER":  {"name": "ACWA Power Company",              "sector": "Utilities",         "price": 98.40,   "vol": 0.020},
        "BUPA_ARABIA": {"name": "Bupa Arabia for Cooperative Ins.","sector": "Financials",        "price": 148.0,   "vol": 0.016},
        "TAWUNIYA":    {"name": "Tawuniya (The Company for Coop.Ins)","sector": "Financials",     "price": 82.40,   "vol": 0.018},
        "GCC":         {"name": "Gulf Cooperation Council",        "sector": "Financials",        "price": 38.40,   "vol": 0.020},
        "ALDREES":     {"name": "Aldrees Petroleum and Transport",  "sector": "Energy",           "price": 48.80,   "vol": 0.018},
        "RABIGH":      {"name": "Rabigh Refining & Petrochemical",  "sector": "Energy",           "price": 8.82,    "vol": 0.025},
        "YANSAB":      {"name": "Yanbu National Petrochemical",    "sector": "Materials",         "price": 48.40,   "vol": 0.018},
        "PETROCHEM":   {"name": "Saudi Petrochemical Company",     "sector": "Materials",         "price": 18.40,   "vol": 0.020},
        "ARSS":        {"name": "Arabian Cement Company",          "sector": "Materials",         "price": 38.40,   "vol": 0.018},
        "QASSIM":      {"name": "Qassim Cement Company",           "sector": "Materials",         "price": 68.40,   "vol": 0.018},
        "YAMAMA":      {"name": "Yamama Cement Company",           "sector": "Materials",         "price": 38.40,   "vol": 0.018},
        "JARIR":       {"name": "Jarir Marketing Company",         "sector": "Consumer Discret.", "price": 148.0,   "vol": 0.016},
        "ALMARAI":     {"name": "Almarai Company",                 "sector": "Consumer Staples",  "price": 48.80,   "vol": 0.013},
        "SAUDIDA":     {"name": "Saudi Dairy & Foodstuff (SADAFCO)","sector": "Consumer Staples", "price": 68.40,   "vol": 0.015},
        "HERFY":       {"name": "Herfy Food Services Co.",         "sector": "Consumer Discret.", "price": 48.40,   "vol": 0.016},
        "EXTRA":       {"name": "United Electronics (eXtra)",      "sector": "Consumer Discret.", "price": 68.40,   "vol": 0.018},
        "WATANIYA":    {"name": "Wataniya Insurance Co.",          "sector": "Financials",        "price": 28.40,   "vol": 0.022},
        "WAFR":        {"name": "Wafrah for Industry & Dev.",      "sector": "Materials",         "price": 18.40,   "vol": 0.020},
        "SAUDI_CABLE": {"name": "Saudi Cable Company",             "sector": "Industrials",       "price": 14.80,   "vol": 0.022},
        "FITAIHI":     {"name": "Fitaihi Holding Group",           "sector": "Consumer Discret.", "price": 18.40,   "vol": 0.025},
        "NATIONAL_ME": {"name": "National Metal Manufacturing",    "sector": "Materials",         "price": 28.40,   "vol": 0.022},
        "MCCI":        {"name": "Middle East Healthcare Company",  "sector": "Healthcare",        "price": 48.80,   "vol": 0.018},
        "DALLAH":      {"name": "Dallah Healthcare Holding",       "sector": "Healthcare",        "price": 98.40,   "vol": 0.016},
        "MOUWASAT":    {"name": "Mouwasat Medical Services",       "sector": "Healthcare",        "price": 148.0,   "vol": 0.016},
        "NAHDI":       {"name": "Al Nahdi Medical Company",        "sector": "Healthcare",        "price": 128.0,   "vol": 0.016},
        "TASNEE":      {"name": "National Industrializ. Co. (Tasnee)","sector": "Materials",      "price": 14.82,   "vol": 0.022},
        "HADCO":       {"name": "Al Jouf Agricultural Dev. Co.",   "sector": "Consumer Staples",  "price": 38.40,   "vol": 0.018},
        "RALS":        {"name": "Abdullah Al Othaim Markets",      "sector": "Consumer Staples",  "price": 98.40,   "vol": 0.014},
        "INMA":        {"name": "Inma Holding Co.",                "sector": "Financials",        "price": 18.40,   "vol": 0.022},
        "AMSA":        {"name": "Advanced Petrochemical Company",  "sector": "Materials",         "price": 48.40,   "vol": 0.020},
        "SIPCHEM":     {"name": "Saudi Int'l Petrochemical (Sipchem)","sector": "Materials",      "price": 18.82,   "vol": 0.020},
        "AIR_ARABIA":  {"name": "Air Arabia (listed on Tadawul)",  "sector": "Transport",         "price": 2.18,    "vol": 0.022},
        "SAUDIA_DYAL": {"name": "Saudi Airlines Catering",         "sector": "Consumer Discret.", "price": 82.40,   "vol": 0.018},
        "RED_SEA":     {"name": "Red Sea International Co.",       "sector": "Industrials",       "price": 28.40,   "vol": 0.020},
    },

    # ── NSE_IN — National Stock Exchange of India (INR) ──────────────────────
    "NSE_IN": {
        "RELIANCE":    {"name": "Reliance Industries Ltd.",        "sector": "Energy",            "price": 2850.0,  "vol": 0.018},
        "TCS":         {"name": "Tata Consultancy Services",       "sector": "Technology",        "price": 4182.0,  "vol": 0.015},
        "HDFCBANK":    {"name": "HDFC Bank Limited",               "sector": "Financials",        "price": 1820.0,  "vol": 0.016},
        "INFY":        {"name": "Infosys Limited",                 "sector": "Technology",        "price": 1580.0,  "vol": 0.016},
        "HINDUNILVR":  {"name": "Hindustan Unilever Limited",      "sector": "Consumer Staples",  "price": 2480.0,  "vol": 0.013},
        "ICICIBANK":   {"name": "ICICI Bank Limited",              "sector": "Financials",        "price": 1248.0,  "vol": 0.016},
        "BHARTIARTL":  {"name": "Bharti Airtel Limited",           "sector": "Communication",     "price": 1580.0,  "vol": 0.018},
        "SBIN":        {"name": "State Bank of India",             "sector": "Financials",        "price": 820.0,   "vol": 0.020},
        "BAJFINANCE":  {"name": "Bajaj Finance Limited",           "sector": "Financials",        "price": 7820.0,  "vol": 0.022},
        "KOTAKBANK":   {"name": "Kotak Mahindra Bank",             "sector": "Financials",        "price": 1820.0,  "vol": 0.016},
        "WIPRO":       {"name": "Wipro Limited",                   "sector": "Technology",        "price": 548.0,   "vol": 0.016},
        "HCLTECH":     {"name": "HCL Technologies Limited",        "sector": "Technology",        "price": 1580.0,  "vol": 0.016},
        "ASIANPAINT":  {"name": "Asian Paints Limited",            "sector": "Materials",         "price": 2980.0,  "vol": 0.015},
        "MARUTI":      {"name": "Maruti Suzuki India Limited",     "sector": "Automotive",        "price": 12480.0, "vol": 0.016},
        "M_M":         {"name": "Mahindra & Mahindra",             "sector": "Automotive",        "price": 2480.0,  "vol": 0.018},
        "TATAMOTORS":  {"name": "Tata Motors Limited",             "sector": "Automotive",        "price": 980.0,   "vol": 0.025},
        "TATASTEEL":   {"name": "Tata Steel Limited",              "sector": "Materials",         "price": 148.0,   "vol": 0.025},
        "ONGC":        {"name": "Oil & Natural Gas Corporation",   "sector": "Energy",            "price": 248.0,   "vol": 0.020},
        "NTPC":        {"name": "NTPC Limited",                    "sector": "Utilities",         "price": 362.0,   "vol": 0.018},
        "POWERGRID":   {"name": "Power Grid Corporation of India", "sector": "Utilities",         "price": 282.0,   "vol": 0.016},
        "ADANIENT":    {"name": "Adani Enterprises Limited",       "sector": "Industrials",       "price": 2480.0,  "vol": 0.035},
        "ADANIPORTS":  {"name": "Adani Ports & SEZ Limited",       "sector": "Transport",         "price": 1248.0,  "vol": 0.025},
        "ADANIGREEN":  {"name": "Adani Green Energy Limited",      "sector": "Energy",            "price": 1820.0,  "vol": 0.040},
        "JSWSTEEL":    {"name": "JSW Steel Limited",               "sector": "Materials",         "price": 820.0,   "vol": 0.022},
        "HINDALCO":    {"name": "Hindalco Industries Limited",     "sector": "Materials",         "price": 680.0,   "vol": 0.022},
        "COALINDIA":   {"name": "Coal India Limited",              "sector": "Energy",            "price": 448.0,   "vol": 0.018},
        "INDUSINDBK":  {"name": "IndusInd Bank Limited",           "sector": "Financials",        "price": 980.0,   "vol": 0.022},
        "AXISBANK":    {"name": "Axis Bank Limited",               "sector": "Financials",        "price": 1148.0,  "vol": 0.018},
        "LT":          {"name": "Larsen & Toubro Limited",         "sector": "Industrials",       "price": 3480.0,  "vol": 0.016},
        "ULTRACEMCO":  {"name": "UltraTech Cement Limited",        "sector": "Materials",         "price": 9820.0,  "vol": 0.016},
        "SHREECEM":    {"name": "Shree Cement Limited",            "sector": "Materials",         "price": 24800.0, "vol": 0.016},
        "DRREDDY":     {"name": "Dr Reddy's Laboratories",         "sector": "Healthcare",        "price": 5820.0,  "vol": 0.018},
        "CIPLA":       {"name": "Cipla Limited",                   "sector": "Healthcare",        "price": 1480.0,  "vol": 0.018},
        "SUNPHARMA":   {"name": "Sun Pharmaceutical Industries",   "sector": "Healthcare",        "price": 1820.0,  "vol": 0.018},
        "DIVISLAB":    {"name": "Divi's Laboratories Limited",     "sector": "Healthcare",        "price": 4820.0,  "vol": 0.018},
        "BIOCON":      {"name": "Biocon Limited",                  "sector": "Healthcare",        "price": 248.0,   "vol": 0.022},
        "TITAN":       {"name": "Titan Company Limited",           "sector": "Consumer Discret.", "price": 3480.0,  "vol": 0.020},
        "NESTLEIND":   {"name": "Nestle India Limited",            "sector": "Consumer Staples",  "price": 24800.0, "vol": 0.013},
        "BRITANNIA":   {"name": "Britannia Industries Limited",    "sector": "Consumer Staples",  "price": 5820.0,  "vol": 0.013},
        "DABUR":       {"name": "Dabur India Limited",             "sector": "Consumer Staples",  "price": 520.0,   "vol": 0.013},
        "GODREJCP":    {"name": "Godrej Consumer Products",        "sector": "Consumer Staples",  "price": 1248.0,  "vol": 0.015},
        "ITC":         {"name": "ITC Limited",                     "sector": "Consumer Staples",  "price": 420.0,   "vol": 0.013},
        "BAJAJFINSV":  {"name": "Bajaj Finserv Limited",           "sector": "Financials",        "price": 1820.0,  "vol": 0.020},
        "HDFCLIFE":    {"name": "HDFC Life Insurance Company",     "sector": "Financials",        "price": 680.0,   "vol": 0.016},
        "ICICIPRULI":  {"name": "ICICI Prudential Life Insurance", "sector": "Financials",        "price": 680.0,   "vol": 0.016},
        "SBILIFE":     {"name": "SBI Life Insurance Company",      "sector": "Financials",        "price": 1480.0,  "vol": 0.016},
        "GRASIM":      {"name": "Grasim Industries Limited",       "sector": "Materials",         "price": 2480.0,  "vol": 0.018},
        "EICHERMOT":   {"name": "Eicher Motors Limited",           "sector": "Automotive",        "price": 4820.0,  "vol": 0.020},
        "BAJAJ_AUTO":  {"name": "Bajaj Auto Limited",              "sector": "Automotive",        "price": 9820.0,  "vol": 0.016},
        "HEROMOTOCO":  {"name": "Hero MotoCorp Limited",           "sector": "Automotive",        "price": 4820.0,  "vol": 0.016},
    },

    # ── EURONEXT — Euronext Pan-European (EUR) ───────────────────────────────
    "EURONEXT": {
        "LVMH":        {"name": "LVMH Moet Hennessy Louis Vuitton","sector": "Consumer Discret.", "price": 582.40,  "vol": 0.020},
        "ASML":        {"name": "ASML Holding N.V.",               "sector": "Technology",        "price": 748.80,  "vol": 0.025},
        "TOTALENERGIES":{"name":"TotalEnergies SE",                "sector": "Energy",            "price": 58.42,   "vol": 0.016},
        "SANOFI":      {"name": "Sanofi S.A.",                     "sector": "Healthcare",        "price": 94.82,   "vol": 0.013},
        "AIRBUS":      {"name": "Airbus SE",                       "sector": "Industrials",       "price": 162.40,  "vol": 0.020},
        "BNPPARIBAS":  {"name": "BNP Paribas S.A.",               "sector": "Financials",        "price": 62.42,   "vol": 0.018},
        "STELLANTIS":  {"name": "Stellantis N.V.",                 "sector": "Automotive",        "price": 14.82,   "vol": 0.025},
        "LOREAL":      {"name": "L'Oreal S.A.",                    "sector": "Consumer Staples",  "price": 348.40,  "vol": 0.014},
        "UNIBAIL":     {"name": "Unibail-Rodamco-Westfield SE",    "sector": "Real Estate",       "price": 62.42,   "vol": 0.022},
        "AXA":         {"name": "AXA S.A.",                        "sector": "Financials",        "price": 32.42,   "vol": 0.016},
        "DANONE":      {"name": "Danone S.A.",                     "sector": "Consumer Staples",  "price": 58.82,   "vol": 0.013},
        "VINCI":       {"name": "Vinci S.A.",                      "sector": "Industrials",       "price": 112.40,  "vol": 0.014},
        "COMPAGNIE":   {"name": "Cie de Saint-Gobain SA",          "sector": "Materials",         "price": 78.42,   "vol": 0.016},
        "HERMES":      {"name": "Hermes International SCA",        "sector": "Consumer Discret.", "price": 2148.0,  "vol": 0.018},
        "SCHNEIDER":   {"name": "Schneider Electric SE",           "sector": "Industrials",       "price": 198.40,  "vol": 0.016},
        "ENGIE":       {"name": "Engie S.A.",                      "sector": "Utilities",         "price": 14.82,   "vol": 0.014},
        "ORANGE":      {"name": "Orange S.A.",                     "sector": "Communication",     "price": 10.82,   "vol": 0.013},
        "SAFRAN":      {"name": "Safran S.A.",                     "sector": "Industrials",       "price": 218.40,  "vol": 0.016},
        "CAP_GEMINI":  {"name": "Capgemini SE",                    "sector": "Technology",        "price": 182.40,  "vol": 0.018},
        "DASSAULT":    {"name": "Dassault Systemes SE",            "sector": "Technology",        "price": 34.82,   "vol": 0.020},
        "MICHELIN":    {"name": "Compagnie Generale des Etablissements Michelin","sector": "Automotive","price": 32.42, "vol": 0.016},
        "RENAULT":     {"name": "Renault S.A.",                    "sector": "Automotive",        "price": 38.42,   "vol": 0.025},
        "PERNOD":      {"name": "Pernod Ricard S.A.",              "sector": "Consumer Staples",  "price": 92.40,   "vol": 0.015},
        "AIR_LIQUIDE": {"name": "Air Liquide S.A.",                "sector": "Materials",         "price": 162.40,  "vol": 0.013},
        "ESSILOR":     {"name": "EssilorLuxottica S.A.",           "sector": "Healthcare",        "price": 182.40,  "vol": 0.014},
        "KERING":      {"name": "Kering S.A.",                     "sector": "Consumer Discret.", "price": 248.40,  "vol": 0.022},
        "PUBLICIS":    {"name": "Publicis Groupe S.A.",            "sector": "Communication",     "price": 98.42,   "vol": 0.016},
        "ING":         {"name": "ING Groep N.V.",                  "sector": "Financials",        "price": 14.82,   "vol": 0.018},
        "PHILIPS":     {"name": "Koninklijke Philips N.V.",        "sector": "Healthcare",        "price": 18.42,   "vol": 0.022},
        "WOLTERS":     {"name": "Wolters Kluwer N.V.",             "sector": "Technology",        "price": 148.40,  "vol": 0.014},
        "AKZO_NOBEL":  {"name": "Akzo Nobel N.V.",                 "sector": "Materials",         "price": 62.42,   "vol": 0.015},
        "RANDSTAD":    {"name": "Randstad N.V.",                   "sector": "Industrials",       "price": 42.82,   "vol": 0.018},
        "ASM_INT":     {"name": "ASM International N.V.",          "sector": "Technology",        "price": 498.40,  "vol": 0.028},
        "NN_GROUP":    {"name": "NN Group N.V.",                   "sector": "Financials",        "price": 38.42,   "vol": 0.016},
        "FERRARI":     {"name": "Ferrari N.V.",                    "sector": "Automotive",        "price": 348.40,  "vol": 0.018},
        "UNICREDIT":   {"name": "UniCredit S.p.A.",                "sector": "Financials",        "price": 38.42,   "vol": 0.018},
        "INTESA":      {"name": "Intesa Sanpaolo S.p.A.",          "sector": "Financials",        "price": 3.82,    "vol": 0.018},
        "ENI":         {"name": "Eni S.p.A.",                      "sector": "Energy",            "price": 14.82,   "vol": 0.016},
        "ENEL":        {"name": "Enel S.p.A.",                     "sector": "Utilities",         "price": 6.82,    "vol": 0.014},
        "LEONARDO":    {"name": "Leonardo S.p.A.",                 "sector": "Industrials",       "price": 24.82,   "vol": 0.018},
        "INDITEX":     {"name": "Inditex (Zara parent) S.A.",      "sector": "Consumer Discret.", "price": 42.82,   "vol": 0.015},
        "BBVA":        {"name": "BBVA S.A.",                       "sector": "Financials",        "price": 9.82,    "vol": 0.018},
        "IBERDROLA":   {"name": "Iberdrola S.A.",                  "sector": "Utilities",         "price": 12.82,   "vol": 0.014},
        "AMADEUS":     {"name": "Amadeus IT Group S.A.",           "sector": "Technology",        "price": 62.42,   "vol": 0.018},
        "EIFFAGE":     {"name": "Eiffage S.A.",                    "sector": "Industrials",       "price": 98.42,   "vol": 0.014},
        "BOUYGUES":    {"name": "Bouygues S.A.",                   "sector": "Industrials",       "price": 32.42,   "vol": 0.016},
        "STMICRO":     {"name": "STMicroelectronics N.V.",         "sector": "Technology",        "price": 22.42,   "vol": 0.025},
        "WORLDLINE":   {"name": "Worldline S.A.",                  "sector": "Technology",        "price": 6.82,    "vol": 0.035},
        "SOCIETE":     {"name": "Societe Generale S.A.",           "sector": "Financials",        "price": 28.42,   "vol": 0.022},
        "CREDIT_AG":   {"name": "Credit Agricole S.A.",            "sector": "Financials",        "price": 14.82,   "vol": 0.018},
    },
}


def get_venue_symbols_for_pipeline():
    return {venue: {sym: data for sym, data in cos.items()} for venue, cos in COMPANIES.items()}


def get_all_companies_flat():
    rows = []
    for venue, companies in COMPANIES.items():
        for sym, data in companies.items():
            rows.append({"venue": venue, "symbol": sym, **data})
    return rows


def get_top_companies_js():
    result = {}
    for venue, companies in COMPANIES.items():
        result[venue] = [{"t": sym, "n": d["name"], "s": d["sector"]} for sym, d in companies.items()]
    return result
